"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { BlockTypeSlug } from "@/types/blocks";

type Variant = {
  id: string;
  name: string;
  snapshot_url: string | null;
};

type Props = {
  currentId: string;
  typeSlug: BlockTypeSlug;
  typeName: string;
  variants: Variant[];
};

const PAGE_SIZE = 4;

/**
 * Horizontal row of variant tiles. Each tile shows a cached WebP snapshot
 * of that block (generated by the editor on save). If a snapshot hasn't
 * been generated yet, shows a "No preview" placeholder — open that block
 * and save to regenerate.
 */
export default function VariantCarousel({
  currentId,
  typeSlug,
  typeName,
  variants,
}: Props) {
  const [page, setPage] = useState(0);
  const pages = Math.max(1, Math.ceil(variants.length / PAGE_SIZE));
  const window = useMemo(
    () => variants.slice(page * PAGE_SIZE, page * PAGE_SIZE + PAGE_SIZE),
    [variants, page],
  );

  if (variants.length <= 1) {
    return (
      <section className="mb-8">
        <h3 className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-anamaya-charcoal/60">
          Variants
        </h3>
        <p className="rounded-md bg-white px-4 py-3 text-sm italic text-anamaya-charcoal/60 ring-1 ring-zinc-200">
          This is the only {typeName.toLowerCase()}. Duplicate it to create a variant.
        </p>
      </section>
    );
  }

  return (
    <section className="mb-8">
      <header className="mb-2 flex items-center justify-between">
        <h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-anamaya-charcoal/60">
          Variants ({variants.length})
        </h3>
        {pages > 1 && (
          <div className="flex items-center gap-2 text-xs text-anamaya-charcoal/60">
            <button
              type="button"
              onClick={() => setPage((p) => Math.max(0, p - 1))}
              disabled={page === 0}
              className="rounded-full border border-zinc-300 bg-white px-2.5 py-1 text-[11px] font-semibold hover:bg-zinc-50 disabled:opacity-30"
              aria-label="Previous variants"
            >
              ‹
            </button>
            <span>
              {page + 1}/{pages}
            </span>
            <button
              type="button"
              onClick={() => setPage((p) => Math.min(pages - 1, p + 1))}
              disabled={page >= pages - 1}
              className="rounded-full border border-zinc-300 bg-white px-2.5 py-1 text-[11px] font-semibold hover:bg-zinc-50 disabled:opacity-30"
              aria-label="Next variants"
            >
              ›
            </button>
          </div>
        )}
      </header>

      <ul className="grid gap-3" style={{ gridTemplateColumns: `repeat(${PAGE_SIZE}, minmax(0, 1fr))` }}>
        {window.map((v) => (
          <li key={v.id}>
            <Link
              href={`/admin/blocks/${v.id}`}
              className={`block overflow-hidden rounded-md bg-white transition-all ${
                v.id === currentId
                  ? "ring-2 ring-anamaya-green"
                  : "ring-1 ring-zinc-200 hover:ring-anamaya-charcoal/30"
              }`}
            >
              <div className="border-b border-zinc-100 px-3 py-2 text-xs">
                <div className="truncate font-semibold text-anamaya-charcoal">
                  {v.name}
                </div>
                {v.id === currentId && (
                  <div className="text-[10px] font-semibold uppercase tracking-wider text-anamaya-green">
                    Editing
                  </div>
                )}
              </div>
              <div className="aspect-[16/3] bg-zinc-50">
                {v.snapshot_url ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={v.snapshot_url}
                    alt={`Preview of ${v.name}`}
                    className="h-full w-full object-contain"
                    loading="lazy"
                  />
                ) : (
                  <div className="flex h-full items-center justify-center text-[10px] italic text-anamaya-charcoal/40">
                    No preview yet — open and save
                  </div>
                )}
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}
