-- Bulk-insert per-category testimonial assignments + excerpts.
-- Generated from manual analysis of all 142 imported TripAdvisor reviews.
-- Each row pairs a category (testimonial_sets.slug) with a review
-- (testimonials.review_id) and the 1–2 sentence sound-bite excerpt
-- to display on that category's carousel.
--
-- Categories used:
--   cuisine          64
--   wellness         36
--   retreats         99
--   homepage         35
--   ytt              9
--   accommodations   38
--   surfing          18
-- Total: 299 assignments

-- Wipe any existing assignments first so this migration is idempotent.
truncate public.testimonial_set_items;

with assignments(slug, review_id, sort_order, excerpt) as (
  values
  ('cuisine', 'r1052702616', 0, 'The food was absolutely spectacular — and as someone with celiac disease, knowing that everything was completely gluten-free was a level of stress relief I never get to experience on vacation. Being able to fully relax and enjoy every meal without worry was such a gift.'),
  ('wellness', 'r1052702616', 0, 'The spa services… I honestly couldn''t get enough. Do yourself a favor and spend some time with Diane — not only is she incredibly skilled, but she''s also just lovely to chat with.'),
  ('retreats', 'r1052702616', 0, 'If you''re considering a wellness retreat, this is your sign. Anamaya is something truly special.'),
  ('homepage', 'r1052702616', 0, 'I just returned from the most incredible stay at Anamaya, and I can''t recommend it enough. From the moment I arrived, everything exceeded my expectations.'),
  ('homepage', 'r1049995938', 1, 'We had such a beautiful and restorative week at Anamaya. The food, accommodations, classes, staff, guests and overall energy was top notch.'),
  ('retreats', 'r1049995938', 1, 'This is my second time doing a retreat at Anamaya so I had high expectations but everything still exceeded. We will be coming back again for sure.'),
  ('ytt', 'r1045214098', 0, 'The staff booked everything for me, from the ferry to the hotels after the YTT. Anamaya Resort has my heart really.'),
  ('cuisine', 'r1045214098', 1, 'The food is some of the best in Montezuma, hands down. Every meal was fresh, flavorful, and nourishing.'),
  ('accommodations', 'r1045214098', 0, 'The rooms and common areas are spotless, comfortable, and surrounded by nature, with views of the jungle and ocean that make it easy to relax.'),
  ('wellness', 'r1045214098', 1, 'They have two huge shalas with ocean view, spa, cold plunge, pool, and a sauna.'),
  ('homepage', 'r1045214098', 2, 'I stayed at Anamaya in Montezuma, Costa Rica, and the overall experience was a dream from start to finish. The entire place is genuinely beautiful, well cared for, and thoughtfully put together.'),
  ('ytt', 'r1041786160', 1, 'I will forever be grateful for a superb 3 weeks stay at Anamaya during my yoga teacher training course. Anamaya is a true paradise and the staff is like family.'),
  ('cuisine', 'r1041786160', 2, 'The food which is anti-inflammatory is so delicious and will make you feel totally rejuvenated.'),
  ('cuisine', 'r1037771711', 3, 'The food, fresh picked from their farm, fresh day boat fish, fruits, vegetables all carefully crafted by a competent team of kitchen warriors.'),
  ('retreats', 'r1037713085', 2, 'What a fantastic experience. Anamaya felt like home right away. Would definitely recommend to whoever wants to spend some time in paradise on earth.'),
  ('wellness', 'r1002851758', 2, 'Anamaya is a sacred place that strengthens the mind and body. Joseph guided us through outstanding programming — including breath work that for me is life-changing.'),
  ('retreats', 'r1002851758', 3, 'Anamaya works its magic by providing healthy, delicious food, yoga, breath work, lovely rooms (with the best balconies overlooking the jungle) and artistic attention to detail throughout the resort.'),
  ('accommodations', 'r1002851758', 1, 'Lovely rooms with the best balconies overlooking the jungle, tropical flower arrangements, beautifully set tables for dinner. And Costa Rican coffee always ready at 6:00 am.'),
  ('homepage', 'r1002851758', 3, 'Anamaya''s spirit is alive… and remains with you. I hope my path always guides me back to Anamaya. It is Sacred Medicine.'),
  ('surfing', 'r1002126669', 0, 'The surfing is 100% worth it, even if just for the beautiful hike to the sandy surfing beach.'),
  ('cuisine', 'r1002126669', 4, 'Every single plate of food was delicious and I never felt hungry.'),
  ('accommodations', 'r1002126669', 2, 'My room, lotus, was extremely comfortable and clean. I spent a lot of time on my balcony''s hammocks, enjoying the view and breeze.'),
  ('wellness', 'r1002126669', 3, 'The spa treatments were all incredible.'),
  ('retreats', 'r1002126669', 4, 'I am so grateful to have chosen Anamaya as the destination for my yoga retreat. Karen Love, yoga retreat leader, is a beautiful soul who inspired me in my yoga practice.'),
  ('accommodations', 'r984556540', 3, 'I stayed in the Anahata room and Lotus Cabina which both have wonderful views. The Lotus Cabina was my favourite of the two, for the cosy feel and the deck.'),
  ('wellness', 'r984556540', 4, 'The spa treatments are a must! Don''t leave without having one. If you like a deeper massage, I recommend the Ashiatsu massage. It''s intense but so freeing!'),
  ('cuisine', 'r984556540', 5, 'The FOOD IS AMAZING! You will feel nourished and fulfilled with the incredible, hearty, great meals they provide. They hit the jack pot on flavour and satisfaction every time.'),
  ('retreats', 'r984556540', 5, 'A perfect getaway for all, especially solo travellers who want to enjoy the good things in life, rest, recover and make new friends.'),
  ('cuisine', 'r968925006', 6, 'The food is healthy, fresh and almost all of it comes from their permaculture farm.'),
  ('homepage', 'r968925006', 4, 'This is one of the most magical places on the planet. The views are second to none with a 270 degree panoramic look at miles of jungle and ocean.'),
  ('retreats', 'r968925006', 6, 'The staff is so personable that they will instantly welcome you as their family. Definitely join a retreat or just come visit.'),
  ('surfing', 'r963482111', 1, 'Nearby activities (zipline, beach, surfing, etc.) fun and easy to get to.'),
  ('cuisine', 'r963482111', 7, 'The food was delicious, and the kitchen asked each of us our preferences and provided accordingly.'),
  ('retreats', 'r963482111', 7, 'This trip really exceeded all expectations. The place is as beautiful as the pictures would suggest! The yoga teacher (Cristiane) was awesome, and provided options for all levels.'),
  ('wellness', 'r929297073', 5, 'The food, the location, the daily morning yoga, evening restorative yoga, meditation & acro yoga workshops & spa treatments helped my mind, body & heart be restored & heal.'),
  ('retreats', 'r929297073', 8, 'Anamaya is such a spectacular experience! I went with a friend for a yoga & wellness retreat. Our yoga instructor Carrie Ingham was incredible!'),
  ('accommodations', 'r913970228', 4, 'I traveled solo and stayed in the Gaia house and my week couldn''t have been more perfect. I felt 100% safe and cared for the entire time.'),
  ('retreats', 'r913970228', 9, 'This place is hands down one of the most amazing and magical places on Earth. If you''re considering booking a trip here, just do it. You will fall in love with this place.'),
  ('homepage', 'r913970228', 5, 'The views are absolutely incredible. Looking up during yoga to see the jungle and the ocean was a moving experience in itself. My heart will be longing for that yoga deck for the rest of my days.'),
  ('wellness', 'r913970228', 6, 'The food is delicious, the people rock, the spa is excellent, and the pool is stuff out of dreams.'),
  ('retreats', 'r913942781', 10, 'The location is stunning. Overlooking the ocean, with a disappearing pool, open air living room, common dining room with fresh flowers on every table.'),
  ('cuisine', 'r913942781', 8, 'We dined on healthy, delicious and pretty food, three times a day.'),
  ('homepage', 'r913942781', 6, 'It ranks in the top vacations of my life and I''ve been to Italy, Kenya, Mexico and other countries. It is all the above things, combined together that made this a special week.'),
  ('homepage', 'r899578040', 7, 'This is the most beautiful, most unique and most special place. Joseph and all staff were universally kind and understanding of all challenges.'),
  ('retreats', 'r893153108', 11, 'The most amazing week. I cannot recommend Anamaya enough. I went as a solo traveler and had the best time. It felt very easy to show up alone.'),
  ('cuisine', 'r893153108', 9, 'The food was incredible. I was blown away by how delicious, fresh, healthy and clean it all was. Fresh coconut milk in my coffee every morning was a highlight.'),
  ('accommodations', 'r893153108', 5, 'I stayed in a single person room which was lovely. Very clean, AC, private bathroom, quiet and a view of the ocean.'),
  ('wellness', 'r885666253', 7, 'The body work offered is incredible, and definitely world class.'),
  ('retreats', 'r885666253', 12, 'Anamaya is an amazing retreat up on a mountain overlooking the ocean. The Anamaya experience has it all — breathtaking views, outstanding staff, delicious food, and beautiful well planned accommodation.'),
  ('homepage', 'r885666253', 8, 'The Anamaya experience has it all — breathtaking views, outstanding staff, delicious food, and beautiful well planned accommodation. It is the perfect place to practice yoga, take part in excursions or simply relax.'),
  ('accommodations', 'r880111510', 6, 'I stayed in the loft of Gaia House with 3 other women — it was perfect for a solo traveller.'),
  ('retreats', 'r880111510', 13, 'Anamaya was exactly as pictured — gorgeous views, delicious food, lovely staff. I spent most of my week by the pool or on my deck, looking over the ocean at whales in the distance, and hummingbirds in the trees.'),
  ('retreats', 'r876187837', 14, 'From pulling up on the property to a view so breathtaking it brought tears to my eyes to the beauty of the property at every corner… Anamaya is truly a slice of heaven on earth.'),
  ('accommodations', 'r876187837', 7, 'Taking an outdoor shower with a view of the ocean and monkeys swinging from the trees was an experience I will never forget.'),
  ('homepage', 'r876187837', 9, 'If you need an escape, an amazing vacation, a yoga retreat or time to know yourself a little better look no further.'),
  ('accommodations', 'r876877493', 8, 'The Bali room was perfect — from the air conditioning to the outdoor shower to the hammock overlooking Montezuma.'),
  ('retreats', 'r876877493', 15, 'I went for a week long yoga retreat and I couldn''t have asked for a better location to practice yoga 2 times a day. I highly recommend Anamaya to anyone who wants to practice yoga in paradise!'),
  ('retreats', 'r854366168', 16, 'Just returned from my 1st ever yoga retreat. The team at Anamaya managed to top my expectations. They are kind, hardworking, and caring individuals that go above and beyond to ensure you are comfortable and well cared for during your stay.'),
  ('cuisine', 'r854366168', 10, 'The yoga was top-notch, and the food was a delight at every snack and meal.'),
  ('retreats', 'r839076242', 17, 'Absolutely beautiful setting, delicious meals and a week that left me feeling refreshed like I had been away for a month (in all the best ways).'),
  ('wellness', 'r839076242', 8, 'The spa services… I dare you to try only one… Luxurious. If you are looking for a refresh this is a great place to go.'),
  ('wellness', 'r838485929', 9, 'I enjoyed 3 massages in my one week! Their team is that good! Barbara gave me the best Ashiatsu ever, I saw her twice!'),
  ('retreats', 'r838485929', 18, 'Beautiful facility in the jungle. Most people will need to take 2-3 planes to get there — sounds complicated? Their team are experts at making this easy and take all the stress away.'),
  ('homepage', 'r837384116', 10, 'Following your spiritual yoga experience on the open air deck, picture yourself in a blue tiled pool up in the jungle listening to monkeys and birds and looking down over the ocean, surrounded by lush greenery and colorful flowers.'),
  ('wellness', 'r837384116', 10, 'The spa services are remarkable. I am a restored, balanced person since this trip and truly hope to return one day.'),
  ('retreats', 'r837384116', 19, 'The place itself is gloriously beautiful. The staff is caring, warm, attentive and kind. The food was delicious, creative, healthy and satisfying.'),
  ('cuisine', 'r837384116', 11, 'The food was delicious, creative, healthy and satisfying.'),
  ('retreats', 'r832963809', 20, 'Loved Natalia Chaverri''s retreat week, her yoga/workshop classes were fantastic! She was very welcoming, knowledgeable and a beautiful soul to be around.'),
  ('homepage', 'r832963809', 11, 'The place is beyond beautiful, with top notch healthy food, friendly staff and gorgeous ocean views — and Anamaya has the best infinity pool in town!'),
  ('retreats', 'r823340345', 21, 'Everything was amazing in Anamaya, from the location, the staff, the food, well everything. Lola Rephann was amazing — even for folks new to yoga, she never made us feel out of place.'),
  ('retreats', 'r822571095', 22, 'Anamaya is a magic place. The energy of the place, the food, the scenery, the people… all combined made it an unforgettable experience. Great for solo travelers.'),
  ('retreats', 'r821953197', 23, 'I had an amazing time, great yoga sessions, met wonderful people. The food is healthy and delicious. The view is exquisite. Probably one of the best places to do a yoga retreat.'),
  ('accommodations', 'r821921351', 9, 'The most serene environment, amazing staff, wonderful rooms. I love the food that is provided. The care and attention the staff put into the grounds shows.'),
  ('ytt', 'r819114970', 2, 'I did my YTT at the Anamaya Resort and I could literally not think of a better place to do a YTT. Everything was exceptionally amazing. At one point it almost felt like we were a big family.'),
  ('cuisine', 'r819114970', 12, 'The food was splendid! Provided fresh food from their own farm and great vegan/vegetarian or any dietary request options.'),
  ('accommodations', 'r819114970', 10, 'The rooms are very beautifully designed. I stayed at the Casita dorm and could not have had a better experience. The dorm is equipped with two showers one of which is an outside shower.'),
  ('wellness', 'r819114970', 11, 'There is also a massage service available and the treatment options are insane! Lots of different massage styles are available.'),
  ('retreats', 'r815025173', 24, 'Anamaya was exactly what I was hoping for and so much more. The photos truly do not do it justice. The beauty of the resort has to be seen to be believed.'),
  ('accommodations', 'r815025173', 11, 'I stayed in the jungle cabana and woke up to the beauty of the jungle every morning.'),
  ('retreats', 'r806869521', 25, 'Yoga retreat for beginners or advanced yogis is amazing, mostly thanks to our yoga teacher Lola who through yoga, with her wisdom and experience, made some great life-changing transformations for most of us.'),
  ('cuisine', 'r806869521', 13, 'With amazing food from our wonderful chef Jeff and so much to offer, this is a true oasis.'),
  ('wellness', 'r801808647', 12, 'I highly recommend getting a massage by Marta. I felt like a different person when I got off her table. I had a healing experience on a very deep level.'),
  ('cuisine', 'r801808647', 14, 'The staff made you feel like family, the food nourishes your body, the view and the yoga are amazing.'),
  ('retreats', 'r799782636', 26, 'Anamaya is a magical place in the middle of the Jungle! The staff goes above and beyond to make you feel comfortable and spoiled.'),
  ('cuisine', 'r799782636', 15, 'The food was amazing, creative, delicious and healthy.'),
  ('surfing', 'r797857514', 2, 'The people, the place, the amazing workshops, yoga, surfing, diving, food, and new friends we''ve met, not to mention the gorgeous facilities. It really couldn''t have been better.'),
  ('retreats', 'r797857514', 27, 'My fiancé and I just returned from two weeks at Anamaya, and we can say without a doubt it was the best decision we''ve made in a long time. Anamaya is the best I''ve experienced!'),
  ('homepage', 'r797857514', 12, 'I''m a big fan of retreat-vacations, and have been to a fair amount all over the world. Anamaya is the best I''ve experienced!'),
  ('retreats', 'r797405924', 28, 'Along with yoga twice a day, I also took surfing classes, the cacao ceremony, osha meditation, a cooking demo, had a deep tissue massage, and toured their farm. It was all amazing and I loved every bit.'),
  ('surfing', 'r797405924', 3, 'Along with yoga twice a day, I also took surfing classes, the cacao ceremony, osha meditation, a cooking demo, had a deep tissue massage, and toured their farm.'),
  ('wellness', 'r797405924', 13, 'First, the staff was so kind and genuine that I left feeling like an extended family member. You really feel nurtured during your stay.'),
  ('retreats', 'r774761710', 29, 'Every morning, waking up to the sounds of the jungle, the incredible sunrises, the joy and bliss of it all… caused endorphin rushes of pure gratitude.'),
  ('homepage', 'r774761710', 13, 'The beauty, sounds, smells, tastes, and inner peace I experienced during our week there have sustained me through these crazy times. The service and commitment to excellence was the icing on the cake to the resort itself.'),
  ('cuisine', 'r761539506', 16, 'As a vegan, I was able to order a different meal each day, which doesn''t happen super often. Not only the food was delicious, but the service was consistent and the ocean view was the best I''ve experienced in Costa Rica!'),
  ('accommodations', 'r751945154', 12, 'My jungle cabina was perfect, I loved being surrounded by lush vegetation and wildlife.'),
  ('wellness', 'r751945154', 14, 'The yoga, activities, and spa treatments were also amazing.'),
  ('retreats', 'r751945154', 30, 'My stay at Anamaya Resort was excellent. The resort was beautiful, and the staff and food were amazing.'),
  ('wellness', 'r751230341', 15, 'The treatments — Lomi Lomi four hands and Ashiatsu massage — are the best I''ve ever experienced. Don''t miss the cacao ceremony and chakra workshops!'),
  ('retreats', 'r751230341', 31, 'The yoga guides Kelly and Ted exude love and passion throughout their every contribution and then some. This was such a special experience. It far exceeded my expectations.'),
  ('cuisine', 'r749920889', 17, 'The food was fresh and incredible. I looked forward to every meal (and snack) in the schedule.'),
  ('retreats', 'r749920889', 32, 'The venue, the food, the staff, the instructors, and the community it attracts — wow. I left feeling both rejuvenated and energized in mind, body, and spirit.'),
  ('surfing', 'r749552027', 4, 'The yoga was awesome, the hiking was a perfect way to start every day, the surfing was so much fun, and the food was delicious and healthy.'),
  ('retreats', 'r749552027', 33, 'This trip exceeded my expectations. It was hard to leave this beautiful place.'),
  ('cuisine', 'r749225610', 18, 'Not sure whether it was the beautiful surroundings, yoga twice-daily, or the gourmet gluten free meals direct from the farm — but I felt better than I have in many years.'),
  ('retreats', 'r749225610', 34, 'What an amazing experience. I would definitely go back!'),
  ('retreats', 'r747661276', 35, 'My time at Anamaya was magical. Lucy Hamel, the yoga instructor, was absolutely fantastic! She made every one of the participants totally comfortable and catered to individual needs.'),
  ('cuisine', 'r747661276', 19, 'Chef Jeff is a whiz! He created a variety of unique, well-balanced meals that had us eating really clean, healthy and tasty food.'),
  ('wellness', 'r747661276', 16, 'For those of us who wanted some down time and pampering, the spa treatments were so relaxing! Each of the massage therapists were awesome!'),
  ('accommodations', 'r746765443', 13, 'The rooms are wonderful and the view from the two yoga decks is amazing. Everywhere is very clean.'),
  ('retreats', 'r746765443', 36, 'Anamaya is amazing. The property is very beautiful. Staff is very friendly, well organized and helpful.'),
  ('cuisine', 'r746765443', 20, 'They offer 3 meals a day with organic food which was really good.'),
  ('homepage', 'r746603334', 14, 'This is a magical place. It is hard to put into words what your experience here is… the people, the plants, the yoga decks, the birds, the ocean, the butterflies, the yogis, the food, the local town, the waves… magic and life changing.'),
  ('accommodations', 'r742386445', 14, 'My beautiful room (Gaia) is one of the newest. An exceptional trip that I would recommend to anyone.'),
  ('cuisine', 'r742386445', 21, 'I didn''t expect it (all gluten free/dairy free, mostly vegan) to be so delicious. The staff was incredibly accommodating with food restrictions.'),
  ('retreats', 'r742386445', 37, 'I visited Anamaya for a special New Year''s retreat and had an incredible time. It seemed a good fit for solo travel, couples and families.'),
  ('retreats', 'r742299854', 38, 'We did a workshop and yoga with Cristiane and she was wonderful. She is positive, passionate and creative in all she does. She really made us feel comfortable.'),
  ('cuisine', 'r742299854', 22, 'The food was incredible — so fresh and tasty and they cater to dietary restrictions. We were able to visit the farm where most of the food came from, Rancho Delicioso.'),
  ('retreats', 'r742209139', 39, 'Cristiane was absolutely amazing! You felt all the time, energy, compassion, love, and creativity that she put forth in preparing for all of our yoga activities.'),
  ('cuisine', 'r742209139', 23, 'We had the most amazing and absolutely delicious meals from Rancho Delicioso with vegan options, and all sustainably produced at their farm. The best homemade coconut and oat milks I''ve ever tasted!'),
  ('accommodations', 'r742108824', 15, 'I stayed in Garuda''s nest with 2 friends. 40 stairs up, but what a view! Surrounded by a garden of fresh veggies that they use to cook the meals.'),
  ('cuisine', 'r742108824', 24, 'Food here is gluten free/dairy free, they are very aware and cautious of food allergies and made sure all foods are separate for those who need it.'),
  ('retreats', 'r742108824', 40, 'There were a plethora of activities to do! Horseback riding, zip lining, cooking class, salsa lesson, Spanish lesson, 2 yoga classes per day. Anamaya was just a perfect week of heaven.'),
  ('wellness', 'r742108824', 17, 'Watsu, Reiki, massage, facial, manicure, pedicure! Colynn went out of her way to offer free meditations in the morning prior to yoga class.'),
  ('retreats', 'r742097704', 41, 'Colynn Vosburgh, our yoga instructor, was somehow perfect for what I needed and the yin fusion yoga, meditations, and workshops we had available to us ensured we were able to work physically, emotionally, and mentally on centering ourselves.'),
  ('cuisine', 'r742097704', 25, 'And the food? Out of this world!'),
  ('retreats', 'r737996106', 42, 'Abbé Ciulla is an amazing person and great yoga teacher. She really cares about you and makes her yoga classes a life-changing event.'),
  ('retreats', 'r737908094', 43, 'I had no idea when I stepped onto the gorgeous grounds at Anamaya that I would walk away from this experience feeling transformed and like there was a shift in me mentally and physically.'),
  ('homepage', 'r737908094', 15, 'The yoga teachers they draw are world class and the community of friends you make there is really something I didn''t expect but was a big part of the experience.'),
  ('cuisine', 'r737908094', 26, 'The place itself is absolutely 5 stars, the food was unbelievable and the staff was outstanding.'),
  ('retreats', 'r733644661', 44, 'It''s been 5 months since my trip to Anamaya and I still think about it every day. Heck, I even dream about it. If you are on the fence about going, don''t think, just go. It will change your life.'),
  ('homepage', 'r733644661', 16, 'The minute I stepped out of the taxi and walked onto the grounds, I felt at peace. The sheer beauty and aura of the resort is worth the trip.'),
  ('accommodations', 'r733644661', 16, 'I stayed in the Lotus Room and it was absolutely stunning. The location was very convenient. The room was bright, clean, air conditioned with wifi, and very nicely decorated.'),
  ('cuisine', 'r733644661', 27, 'I never felt hungry, and the food was downright delicious! The chef prepares a new meal every breakfast, lunch, and dinner.'),
  ('wellness', 'r733644661', 18, 'I received a spa treatment almost everyday. There''s a wide variety of massages and services. The spa staff is wonderful and highly skilled.'),
  ('accommodations', 'r733407217', 17, 'We had the Ananda Room. It was like being in a movie. Every morning we awoke to the beautiful sunrise.'),
  ('retreats', 'r733407217', 45, 'Banyan Gallagher the yoga instructor was amazing — intelligent, gentle, helpful, mindful and funny.'),
  ('cuisine', 'r733407217', 28, 'The chef Jeff was creative and prepared the most delicious meals.'),
  ('retreats', 'r733375479', 46, 'I booked my first yoga retreat at Anamaya. It was wonderful. Everything is well organised, staff really really nice and available.'),
  ('surfing', 'r733375479', 5, 'The quality of the instructor really good as well (yoga and surf).'),
  ('cuisine', 'r733296310', 29, 'I have food allergies and they made sure that all of the staff were aware. My food was always served on a blue plate.'),
  ('retreats', 'r733296310', 47, 'The daily yoga classes were great. The environment was indescribably beautiful. They treat you like royalty.'),
  ('ytt', 'r723338178', 3, 'I did the 21-day Yoga Teacher Training with Peter Kaaberbøl and it was just incredible. Always in a good mood, always knowing what to teach and when. Don''t think about it — just let him guide you.'),
  ('cuisine', 'r723338178', 30, 'Chef Jeff and his healthy organic food is always surprisingly and super mega delicious. No matter if you are having breakfast or dinner. 5 meals a day are just outstanding.'),
  ('accommodations', 'r717186674', 18, 'We were greeted warmly and offered fresh coconut milk upon arrival. Yoga spaces are awe-inspiring; the treehouse is a beautiful space to spend a week!'),
  ('retreats', 'r716421197', 48, 'The atmosphere is super friendly, casual and relaxing. Gorgeous setting, lovely and clean accommodations with great views, genuine staff, excellent spa treatments, great yoga classes twice a day.'),
  ('cuisine', 'r716421197', 31, 'A highlight was the tour of their organic farm where all their delicious food comes from.'),
  ('surfing', 'r716421197', 6, 'The beach trip with all the guests and staff (surfing for those that wanted it) was a highlight.'),
  ('retreats', 'r699204968', 49, 'My yoga instructor Cristiane Machado is such a wonderful human being who helped me leave Costa Rica with a new sense of self. She made this experience into more than just a yoga retreat with her wisdom and guidance.'),
  ('accommodations', 'r699204968', 19, 'I stayed in the casita which was lovely. The outdoor shower is amazing.'),
  ('cuisine', 'r699204968', 32, 'The food was amazing, each meal was better than the last. I felt so good by the end of the week.'),
  ('cuisine', 'r698344018', 33, 'You could easily go just for the food — it was that spectacular. Farm to table perfection.'),
  ('retreats', 'r698344018', 50, 'Our instructor Zarelly was unbelievable and every single person provided the highest form of hospitality you can imagine. As adults we are always taking care of someone — for once, we were taken care of.'),
  ('homepage', 'r698344018', 17, 'It''s divine and exceeded all of my very high expectations. Authentically and beautifully, in every way. Our souls are healed.'),
  ('surfing', 'r696330484', 7, 'Came here to Montezuma to surf and also have a great time. The food was absolutely delicious and the place is full of local animals and is in a very untouched state.'),
  ('accommodations', 'r696330484', 20, 'The room where we stayed had a great view of the ocean and we were woken up every morning by the monkeys.'),
  ('wellness', 'r692261851', 19, 'Watsu with Ana is a must do. It is done in a natural pool by the sea. Wonderful connection with nature, amazing food, warm people.'),
  ('accommodations', 'r687249642', 21, 'I stayed in Bali the first week then switched to Garuda''s Nest. My favorite aspects of Bali were the shower with a private ocean view and the private deck. Garuda''s Nest was like living in a treehouse — words cannot do the views justice.'),
  ('cuisine', 'r687249642', 34, 'The food. Wow… what an experience. It was delicious, beautiful, nutritious and made with so much love. Jeff (the chef) is so willing to accommodate any of your dietary needs or wishes.'),
  ('wellness', 'r687249642', 20, 'Spa services were all fantastic. I did various massages and all were expertly done and very therapeutic/restorative; the therapists were very in tune with their client and had a very intuitive flow.'),
  ('retreats', 'r687249642', 51, 'It felt as though this place had been designed especially for me. Every detail in the experience was perfect — it felt as though they read my mind and knew exactly what was perfect for each moment.'),
  ('homepage', 'r687249642', 18, 'Anamaya is heaven on Earth — a place that is a feast for the mind, the heart, the senses, the body, and the soul.'),
  ('accommodations', 'r679958735', 22, 'We stayed in the Bali Cabina and that has by far been the absolute most amazing place I''ve ever stayed. The outdoor bathroom with an ocean view (and a giant bath tub) was so awesome.'),
  ('cuisine', 'r679958735', 35, 'We even went fishing and chef Jeff made a variety of stuff with the fish we caught for everyone to share. The food was super amazing!'),
  ('retreats', 'r679958735', 52, 'The photos do it no justice. Doing yoga on the yoga deck hearing howler monkeys, looking out at the ocean and the mountains was something I''ll never forget.'),
  ('retreats', 'r678784989', 53, 'I loved my yoga teacher, Marcela Nunez! She is the best — so thoughtful and detailed with her practice. Anamaya is truly a magical place — the resort is beautiful and the connection you make with the staff and people at the retreat is really like family.'),
  ('wellness', 'r678784989', 21, 'I ended up getting two massages, one of which was the LOMI LOMI (with the hot oil massage). It is a must. I also got a tarot reading from Diane — highly recommend, it gave me chills.'),
  ('cuisine', 'r678784989', 36, 'Every meal I had was amazing and is locally sourced at their nearby farm. Go Chef Jeff & his team!'),
  ('accommodations', 'r677365895', 23, 'This was a trip of a lifetime. Accommodations are fantastic. We had a group of 5 girls and stayed in Gaia. Lots of room, great bed, open showers, AC and great service.'),
  ('cuisine', 'r677365895', 37, 'Food was amazing. Chef Jeff knows his cooking.'),
  ('wellness', 'r677365895', 22, 'Massage is a must — Lomi Lomi was my fave.'),
  ('ytt', 'r677328311', 4, 'Anamaya is a magical place! Everything from the staff to the food to the rooms is top notch! The staff really becomes like family to you.'),
  ('cuisine', 'r677328311', 38, 'The food is unlike anything I have ever had and all comes from a farm.'),
  ('wellness', 'r670467152', 23, 'If you go, you need to try the Reiki with Diane and the Lomi Lomi massage. I would recommend this resort to anyone, you will not be disappointed!'),
  ('homepage', 'r670467152', 19, 'This resort is spectacular, breathtaking and there is a beautiful energy quality there that is difficult to put into words. I have travelled all over the world and Anamaya is my favourite place.'),
  ('retreats', 'r668666444', 54, 'All I can say is WOW! Excellent service, clean rooms and a life-changing experience. The combination of yoga, meditation, clean eating and fun activities was perfect.'),
  ('wellness', 'r664025751', 24, 'The ultimate kicker was the Lomi Lomi Four Handed massage, a must do here. One of the craziest experiences of my life.'),
  ('cuisine', 'r664025751', 39, 'Every meal I would say this is the best meal I have ever had — just mind-boggling. Chef Jeff slays and the farm is also very cool.'),
  ('homepage', 'r664025751', 20, 'What I would give to start every single day by waking up to sunrise and the sounds of nature, eating fresh fruit, and doing yoga on the most beautiful sundeck ever created overlooking the ocean and jungle. Anamaya is heaven on earth.'),
  ('retreats', 'r663834649', 55, 'What I did not know I would come out with was an awesome new passion for yoga thanks to Kelly and Ted, meditation as a daily practice, healthier eating habits, and a new family of lifelong friends and connections.'),
  ('retreats', 'r659931950', 56, 'Magical is the only word I have to describe my stay at this amazing and intimate resort! Shout out to Malissa Whited — best yoga teacher ever!'),
  ('cuisine', 'r659931950', 40, 'The food was not only delicious and healthy — it was always creatively presented. Kudos to the chef!'),
  ('retreats', 'r658357282', 57, 'This place is magic. I arrived mentally and physically drained. After a kind staff, magical place, epic food, beautiful views, amazing service, memorable massage, a nurturing community, transformational yoga, and mind-blowing accommodations, I came home a new and better person.'),
  ('homepage', 'r658357282', 21, 'The reality was even better than the photos. I have a tree nut allergy and they were super careful and conscientious about taking care of me, making me special meals when needed.'),
  ('wellness', 'r658281196', 25, 'Our yogi, Natasja Payne, provided insightful yoga classes combined with Ayurvedic teachings that nurtured our bodies and souls. Most relaxing and rejuvenating trip I have ever enjoyed.'),
  ('cuisine', 'r658281196', 41, 'The food was farm fresh, organic, gluten free and best of all… absolutely delicious.'),
  ('surfing', 'r656915693', 8, 'Just got back from a week of yoga, surfing and relaxation at Anamaya and I wish I could be back there right now! From the first hello to the (almost) emotional goodbyes, we were made to feel a welcome part of the family.'),
  ('accommodations', 'r656915693', 24, 'We stayed in the Bali room, which offered an amazing view of the coastline while being nicely tucked away behind the main house. All the other accommodations were built to very high standards too.'),
  ('cuisine', 'r656915693', 42, 'Food was very varied and very good. Chef Jeff is very good at coming up with different, interesting and tasty, healthy dishes.'),
  ('retreats', 'r644107017', 58, 'It''s hard to describe something so pleasing on the eye, set in a truly stunning location with panoramic views that are breathtaking — whether you are watching wildlife in the trees or in the air, sunrises or the moon sparkling on the ocean.'),
  ('accommodations', 'r644107017', 25, 'I stayed in the Mantra Room, set immediately beneath the yoga shala used in the evening. I slept what is considered a healthy amount every night while there and I rarely get more than 4 hours unbroken sleep.'),
  ('homepage', 'r644107017', 22, 'The reservations and reception team, gardeners and housekeeping staff were so friendly it was like staying with friends — and nothing was too much trouble.'),
  ('retreats', 'r642616453', 59, 'A totally unique place to stay and explore Montezuma, Costa Rica. Loved the planned activities and yoga schedule. The infinity pool and yoga studios were tops.'),
  ('retreats', 'r642220925', 60, 'Lola, our yoga and meditation instructor for the week, was beyond our expectations. She helped us to grow and deepen our practice so much during the week.'),
  ('cuisine', 'r642220925', 43, 'Our meals were delicious and always fresh and organic. Not having to worry about your next meal and just enjoying your time totally made the trip more enjoyable.'),
  ('surfing', 'r641292400', 9, 'This was the absolute best surf instructor experience I''ve ever had. The instructors split you up in groups of 1-3 people per instructor so you always got exactly what you needed. The beach we went to, Playa Grande, was absolutely perfect for beginner-intermediate.'),
  ('retreats', 'r641292400', 61, 'I just returned from a one-week yoga and surf retreat from Anamaya and could not possibly recommend this place more to anybody, no matter their particular interests.'),
  ('homepage', 'r641292400', 23, 'I never travel the same place twice but I would come back in a heart beat. I have literally zero complaints. This is an incredibly perfect, wonderful, relaxing and adventurous place.'),
  ('cuisine', 'r641292400', 44, 'The food is unbelievable. It was healthy but tasted rich with so many varieties of flavors and textures. Anamaya did an incredible job catering to dietary restrictions, creating entirely different dishes so that everyone could also enjoy the meals.'),
  ('retreats', 'r638973548', 62, 'It''s hard to put into words how special and magical this place is. If you are considering it, just go! The setting is so unique surrounded by the Pacific ocean and jungle. It feels more like home than a resort.'),
  ('retreats', 'r636331178', 63, 'Anamaya provided all of this and even more. I left Anamaya and Costa Rica feeling so much more grounded, at peace, excited and hopeful for the future than I could have imagined.'),
  ('cuisine', 'r636331178', 45, 'I really enjoyed not only eating so cleanly, but also just seeing what kind of unique, refreshing meals can be made without dairy and gluten that aren''t just boring salads.'),
  ('ytt', 'r620004642', 5, 'I have just got back from a 3-week yoga teacher training at Anamaya and I honestly cannot put into words what an incredibly special place Anamaya is. This is one of the rare places where the photos genuinely don''t do it justice. I am now worried no other yoga retreats/courses/trainings are ever going to live up to what I experienced at Anamaya.'),
  ('cuisine', 'r620004642', 46, 'The food is absolutely to die for — you definitely won''t go hungry and you will be consistently amazed by what the kitchen rustle up for you.'),
  ('cuisine', 'r614949678', 47, 'Food is gloriously delicious and truly healthy, fresh, gluten free. Jeff, the chef, is so creative — he uses farm ingredients wisely with health in mind.'),
  ('wellness', 'r614949678', 26, 'Massages are the best I ever got. Recommend Lomi Lomi and deep tissue.'),
  ('homepage', 'r609526554', 24, 'If you are into amazing views, magical happenings, the best food, incredible people and a place that will change you forever, then this is your place!'),
  ('retreats', 'r601168335', 64, 'I visited Anamaya 5 years ago, and said I would visit again. The location is to die for. Surrounded by lush green vegetation, the air you breathe is as pure as can be.'),
  ('cuisine', 'r601168335', 48, 'The food was very delicious. Everyday we had something different. You could taste the freshness of the ingredients and tell the food was prepared with a lot of care.'),
  ('accommodations', 'r601168335', 26, 'Each room has its own individual touch making them all very special but different at the same time. Beds are very comfy. The colors, the furniture, the layout of the spaces makes it to where you can enjoy company or be on your own.'),
  ('retreats', 'r594602835', 65, 'Anamaya Resort & Retreat Center is the best money I have spent on a vacation. I left so relaxed, restored and rejuvenated after my 7-day adventure that I even went back to my stressful television job early.'),
  ('wellness', 'r594602835', 27, 'The spa treatments were excellent — especially the deep tissue massage.'),
  ('retreats', 'r578565337', 66, 'Our yoga instructor for the week, Cristiane Machado, was inspiring, motivating, engaging, and just created a presence that made the week so special.'),
  ('retreats', 'r578557322', 67, 'The instructor, Cristiane, was amazing, funny, compassionate. The classes were adaptable to all levels, from no experience to the pro.'),
  ('retreats', 'r576258848', 68, 'This was my first trip, and I went solo! Anamaya did not disappoint. The other travellers I met there were such an amazing group of people. A few of us are even planning a trip back together!'),
  ('accommodations', 'r572759379', 27, 'The rooms were simple and perfect — but the outdoor bathroom was purely a treat. The pictures do not do this place justice.'),
  ('retreats', 'r572759379', 69, 'The yoga shala overlooking the water and jungles in the evening, with a thunderstorm rolling in, is like nothing we have ever seen — breathtaking.'),
  ('surfing', 'r569794893', 10, 'My friends and I went for a yoga and surf retreat and came back with way more than we expected.'),
  ('accommodations', 'r569794893', 28, 'The outdoor shower and bathroom was the best experience, especially at night, under the stars!'),
  ('retreats', 'r569794893', 70, 'The greatest part of Anamaya is that you can go there to relax and do nothing else but read by the pool, or fill your time with as many activities as you would like, completely up to you.'),
  ('cuisine', 'r569794893', 49, 'The food was amazing, healthy and all dietary needs met.'),
  ('retreats', 'r568914766', 71, 'My friends and I loved Anamaya! The property and housing was beautiful. The staff was wonderful, very helpful, and super organized! I loved all of the additional activities they helped coordinate daily.'),
  ('ytt', 'r566061016', 6, 'I spent three weeks here in January taking Paula Tursi''s yoga teacher training, which was beyond excellent. The resort itself is utterly beautiful, set amongst nature but with a high level of luxury.'),
  ('accommodations', 'r566061016', 29, 'I was lucky enough to have a room with a semi-outdoor bathroom and a private terrace with a hammock. This meant I could shower whilst watching whales in the ocean or see the stars without light pollution.'),
  ('surfing', 'r566037605', 11, 'The surf lessons are totally adapted to the beginner level and the teachers are very serious.'),
  ('retreats', 'r566037605', 72, 'The place is beautiful, the food is amazing and the on-site organization is impeccable. The staff at Anamaya are fantastic and attentive to your needs.'),
  ('homepage', 'r565272378', 25, 'There is a genuine warmth you feel from the staff, who go out of their way to make your stay amazing. By the end of my week I felt the staff were part of my family and myself part of the Anamaya family.'),
  ('homepage', 'r561606664', 26, 'This place is fantastic! Gorgeous grounds, fantastic people working there, the food is unbelievable. It is so much more than just a vacation.'),
  ('retreats', 'r561606664', 73, 'This place is fantastic! Gorgeous grounds, fantastic people working there, the food is unbelievable. I will definitely be back and I never go to the same place twice.'),
  ('accommodations', 'r560046375', 30, 'The rooms are clean and beautiful. Some have outdoor showers, which is such a luxury.'),
  ('surfing', 'r560046375', 12, 'The arranged tours and adventures — like surfing and zip-lining — were fantastic.'),
  ('cuisine', 'r560046375', 50, 'The food is so healthy and delicious — much of it is grown on their nearby farm.'),
  ('retreats', 'r560046375', 74, 'I cannot recommend Anamaya highly enough. It is incredible in every way. The yoga decks had the most amazing views. Each and every one of the staff members were so kind, helpful, patient, and cheerful.'),
  ('accommodations', 'r559900425', 31, 'Our room (Hanuman) was large, bright and a perfect place to wake up to the sunrise every morning. There were two very comfortable king-sized beds and a beautiful outdoor washroom — so nice to shower and look out over the jungle and ocean!'),
  ('retreats', 'r559900425', 75, 'It was an amazing experience from arrival to departure. The staff were wonderful and caring — felt like family after the first day! They look after every need and are customer service professionals.'),
  ('cuisine', 'r559900425', 51, 'The food was unbelievable — fresh and plentiful and never repetitive. They serve a gluten-free, dairy-free menu with many options.'),
  ('retreats', 'r553270833', 76, 'Anamaya is an amazing place! Excellent service, beautiful and clean quarters, delicious healthy food, and thoughtful retreat programming. Feels secluded yet cozy.'),
  ('retreats', 'r553042721', 77, 'This was my second time at Anamaya and my only concern in coming back was — my first trip was perfect, how could the second not be a let down? The staff, the food, the grounds, everything absolutely perfect once again.'),
  ('homepage', 'r552939088', 27, 'Anamaya is my home away from home. Everything about the trip — from the room to the staff to the yoga teacher, to the amazing food, to the pool, to the treatments — was absolutely mind-blowing and worth every penny.'),
  ('ytt', 'r545504875', 7, 'I never imagined I would go through such a positive transformational program and feel such a great change in myself. Thank you Jackie for the amazing program. Everything was organized so perfectly that I could just focus on my own journey.'),
  ('cuisine', 'r545504875', 52, 'The first day, trying the food, I was smiling for a solid hour after eating. The freshness and taste of the food was indescribably good.'),
  ('wellness', 'r543458293', 28, 'Watsu is a once-in-a-lifetime experience of rebirth. Ana Laura takes you to her favorite tide pool where she creates the conditions for you to discover areas of your body that have been tight from anxiety or stress, then uses the peaceful ocean to wash away old thoughts.'),
  ('retreats', 'r543458293', 78, 'From the moment I started planning for my trip I felt supported and cared for. The staff was willing to go out of their way to make sure they took care of all my needs so that I could relax and enjoy everything Costa Rica had to offer.'),
  ('accommodations', 'r542677538', 32, 'I had the pleasure of staying in the beautiful Bali Cabina… Wow! Amazing!'),
  ('wellness', 'r542677538', 29, 'Make sure that you visit one of the many great spa services available — and if possible, please try the Watsu Healing Therapy with AnaLaura. A wonderful experience like no other.'),
  ('retreats', 'r542677538', 79, 'Anamaya is nothing short of magical! The staff at Anamaya are hands down the most welcoming and accommodating that I have ever experienced — by the time you are ready to leave, they have become family.'),
  ('retreats', 'r541183379', 80, 'This place is really magical. Everything about it was perfect, from the room to the food. All of the staff is phenomenal and so welcoming. The view is endless and gets better and better the more you look at it.'),
  ('accommodations', 'r539989486', 33, 'I had the master suite, just above the main house. This was a convenient location and had a beautiful view.'),
  ('cuisine', 'r539989486', 53, 'The food was sooo good and healthy. We were trying to convince the staff to put out a recipe book.'),
  ('wellness', 'r539677522', 30, 'For a most unique and transformative, nurturing experience, you must have a Watsu massage with Ana Laura — it will touch you to your core! The staff in the spa are masterful, offering highly skilled and diverse services.'),
  ('retreats', 'r539677522', 81, 'Anamaya offers the perfect balance between movement and rest, indulgence and health, introspection and interaction. A random gathering of people from around the globe with similar intent means fast friendships and a depth of connection unique to the intimate setting.'),
  ('cuisine', 'r539677522', 54, 'The food from Rancho Delicioso, with the creative mind of chef Jeff, is exemplary and can be compared to any high-end restaurant anywhere.'),
  ('homepage', 'r539677522', 28, 'At Anamaya, the body and mind are nurtured in a way we rarely experience in our day to day lives. It is extraordinary to see people truly relax. This place, with its stunning physical beauty, is where you must go. As a gift to yourself… Anamaya. It''s magic!'),
  ('retreats', 'r534386948', 82, 'This was my first ever yoga retreat, and I cannot gush about my experience at Anamaya enough. Everything for the week was beyond my expectations. The staff at Anamaya was like a family and they cared for us like we were family.'),
  ('homepage', 'r534386948', 29, 'I honestly came home a better person. All the fears I had about traveling there were completely irrelevant in comparison to the amazing, transformative time I had while I was there. I''m already dreaming of going back.'),
  ('cuisine', 'r534386948', 55, 'I honestly have no appetite since returning because I was so incredibly spoiled while we were there — such nourishing, healthy, stunning food.'),
  ('retreats', 'r528828792', 83, 'From the staff, to the managers at the hotel, the yoga, the amenities and to the hotel rooms, and the food. The stunning views — Anamaya is truly in my view a gem!'),
  ('homepage', 'r528828792', 30, 'You made me more healthy — mentally, emotionally and physically. I know why they call Nicoya a blue zone! If I lived there I would definitely live longer.'),
  ('retreats', 'r501956180', 84, 'I''m one week back from Anamaya and I''m pretty sure the experience has changed me forever. It has the best of everything when it comes to Costa Rican resorts — but Anamaya is also an experience and a way of life.'),
  ('surfing', 'r501956180', 13, 'The activities are top-rate from the ziplining to the surfing instruction. Wildlife — from monkeys to butterflies and hummingbirds — abounds.'),
  ('homepage', 'r501956180', 31, 'If you are tired, burnt out or just needing to shake things up, get yourself to Anamaya ASAP!'),
  ('cuisine', 'r501956180', 56, 'The food is fresh, creative and delicious — healthy and whole, but you can still indulge in a good cup of coffee or glass of wine.'),
  ('surfing', 'r497794287', 14, 'Of course there is yoga, but if you want excitement, there are waterfalls, hikes, boat trips with snorkeling and surfing on the beautiful beaches.'),
  ('wellness', 'r497794287', 31, 'I had the privilege of doing Watsu with Ana and Reiki, which for me was a very powerful experience after already being in such a spiritual and happy place.'),
  ('retreats', 'r497794287', 85, 'This place is incredible — as soon as you walk on their property you feel welcomed and more relaxed. The views from the back are spectacular and pretty much every single room has a different view of the beautiful grounds.'),
  ('retreats', 'r491790808', 86, 'It''s not just the amazing views from the infinity pool, or the out-of-this-world food where you''ll feel like a kid anxiously looking forward to the next meal, or the massages, or the yoga classes that will challenge you and rejuvenate you at the same time… it''s all that, plus the amazing people you meet.'),
  ('homepage', 'r491790808', 32, 'It''s been a week since I''m back home and I''m still in full withdrawal mode. Stop thinking about it and just go — you won''t regret it.'),
  ('retreats', 'r490788002', 87, 'I spent weeks looking at reviews and prices for a yoga retreat. Finally took the leap and booked Anamaya. I cannot describe how perfect this place is — the staff, the food, the location, the views — everything is outstanding. I left the retreat feeling completely rejuvenated.'),
  ('cuisine', 'r484417044', 57, 'The food is outstanding and plant-based!'),
  ('wellness', 'r484417044', 32, 'The spa has so many choices you could stay 2 weeks and do 2 treatments a day and not try everything.'),
  ('retreats', 'r484417044', 88, 'This retreat is fantastic! The yoga is fabulous as is the areas you do your yoga classes in. The grounds and accommodations are tropical and very blended with the natural flora and fauna.'),
  ('surfing', 'r483635132', 15, 'Father/daughter trip to Anamaya was more than we could have dreamed. The amazing food, perfectly presented, twice-daily yoga with Kat and trips to great surf breaks and other adventures in between left us feeling great.'),
  ('retreats', 'r483635132', 89, 'The staff is very helpful about getting your details in order both with travel and once you are there.'),
  ('homepage', 'r480514672', 33, 'Stop searching for any other places to visit in Costa Rica and book your trip to Anamaya now! The resort is situated overlooking the pristine jungle and ocean — I heard the waves crashing against the shore all week long from my room and the main dining area.'),
  ('retreats', 'r480514672', 90, 'The staff is amazing — so warm and caring. They handle every detail to ensure you have the best experience. I loved the pool and the yoga deck where we greeted the sunrise each morning during our practice.'),
  ('wellness', 'r476460505', 33, 'Do the Watsu with Ana — it is life changing!'),
  ('retreats', 'r476460505', 91, 'The staff are the absolute best ever! They are kind, talented, and detail-oriented. You leave feeling like they are your family. The resort is utterly breathtaking and the food is amazing!'),
  ('retreats', 'r441198962', 92, 'I had such a healthy, fun experience. Yoga on a deck above the ocean. Food was delicious and healthy. Lots to do or just hang out. People are amazing there.'),
  ('wellness', 'r440962120', 34, 'Excellent add-on therapies — Reiki and Watsu were amazing! The friendly service throughout made it a very special week.'),
  ('retreats', 'r440962120', 93, 'This is a wonderful, friendly retreat offering first-class facilities. The accommodation is lovely, the yoga and the studios very special. The food was out of this world.'),
  ('retreats', 'r437140731', 94, 'The location (especially the stellar view from the yoga deck) cannot be beat. The infinity pool was awesome. We had awesome people on our retreat from all over the world. It was like summer camp for grown ups in the best possible way.'),
  ('cuisine', 'r437140731', 58, 'The food was delicious and healthy. My cousin is a vegan and I eat everything and we both were satisfied — they go out of their way to accommodate different diets and allergies.'),
  ('surfing', 'r426225377', 16, 'I was looking for a place to escape the world for a week, and unwind with yoga, massages, and surfing.'),
  ('accommodations', 'r426225377', 34, 'I stayed in the Prana Cabina, which was perfect for a solo traveler looking for alone time.'),
  ('wellness', 'r426225377', 35, 'Definitely do the Watsu water massage, especially if you''re there in need of healing.'),
  ('cuisine', 'r426225377', 59, 'The food was incredible. I loved touring the organic farm. I cannot wait until the cookbook comes out.'),
  ('retreats', 'r415799919', 95, 'From the moment I stepped foot onto Anamaya''s property, I felt the magic in and around my soul. I felt like home immediately. Everyone there is a like-minded individual, looking for the same things in their life at that moment.'),
  ('homepage', 'r415799919', 34, 'You need to go here, soon. You won''t regret it, and it will change your life.'),
  ('cuisine', 'r415799919', 60, 'The food is out of this world. Everything is so healthy and delicious. My stomach had never been happier than it was that one week.'),
  ('accommodations', 'r415799919', 35, 'It is like one big home, with many small guest houses littered around the jungle property. From almost anywhere you have a sweeping ocean view. Everything is beautiful, and the decor is very Moroccan and comforting.'),
  ('retreats', 'r415064090', 96, 'The rooms are beautiful and spotless. This place is truly amazing! While the property is absolutely beautiful, the best part is the staff — they make everything so easy.'),
  ('cuisine', 'r415064090', 61, 'The food was also amazing and totally inspired me to eat more of a plant-based diet.'),
  ('surfing', 'r405269468', 17, 'This location, staff, and schedule of activities is everything you could ever ask for in a surf and yoga camp.'),
  ('retreats', 'r396930946', 97, 'My mom and I booked this trip for my college graduation gift and it was more than I ever expected. We did the week yoga retreat with the adventure package. Everyone makes you feel right at home. The food and views are unreal!'),
  ('accommodations', 'r393916484', 36, 'All the rooms are unique (I stayed in the Ganesh cabin, which was amazing) and the staff becomes like family.'),
  ('retreats', 'r393916484', 98, 'I can not say enough about this wonderful place. I was traveling by myself and picked this resort based on other TripAdvisor reviews, and I was not disappointed.'),
  ('cuisine', 'r393916484', 62, 'The food is amazing and the yoga decks have the most perfect views.'),
  ('ytt', 'r390272117', 8, 'This is my second time here — I visited first for a one-week yoga retreat, and came back for a four-week teacher training. The experience was consistently incredible.'),
  ('accommodations', 'r390272117', 37, 'I''ve stayed in both the Gaia House and Garuda''s Nest (the treehouse). The views from the unique accommodations on the property are breathtaking. Any pictures you see online just don''t do it justice.'),
  ('cuisine', 'r390272117', 63, 'Chef Jeff and his team create delicious gluten-free meals and are very accommodating to any other dietary needs. You can tell a lot of love goes into the cooking — it''s so tasty and beautifully presented.')
)
insert into public.testimonial_set_items (set_id, testimonial_id, sort_order, excerpt)
select s.id, t.id, a.sort_order, a.excerpt
from assignments a
join public.testimonial_sets s on s.slug = a.slug
join public.testimonials t on t.review_id = a.review_id;

-- Sanity check
do $$
declare cnt int;
begin
  select count(*) into cnt from public.testimonial_set_items;
  raise notice 'testimonial_set_items row count after assignment import: %', cnt;
end $$;
