-- ============================================================
-- 0076: Convert 4 more real retreat pages to the retreat template
--
-- Retreats: Regulate (Colynn Cespedes), The Art of Thriving
-- (Leslie Lutsch + Colleen Navas, co-taught), The Anatomy of
-- Sacred Breath (Cristiane Machado), Awaken Your Path (Missy +
-- David Hartley, co-taught). Content from the already-reviewed
-- retreat_imports extraction (0 warnings each). Cristiane and
-- Leslie/Colleen are real AnamayOS-linked people, so their leader
-- cards use ao_person_id (live) with the scraped bio as fallback.
--
-- Two of these retreats have both a v1 and v2 url_inventory row;
-- both get the same override + cms_template_id so whichever one
-- getRetreatBySlug's newest-wins tie-break picks still renders
-- correctly.
--
-- Three of these four have no registration_link in AnamayOS (only
-- a self-referencing external_link, or nothing) -- their Book
-- button points at the site's real current booking page
-- (https://anamaya.com/rg-calendar/) instead of a guessed Retreat Guru URL.
-- ============================================================

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/ee6afaac-3f31-42b9-a5d4-feea52aa96e4/gallery/hero-image-82-5d39039d.png", "image_alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"html": "<h1 style=\"text-align:center\">Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes</h1><p style=\"text-align:center\">with Colynn Cespedes</p>", "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "0f61bab5-bdea-46e7-8953-2dfa3db35cc6", "heading": "Dates & Rates", "manual_dates_text": "Oct 31 - Nov 7, 2026", "manual_tiers": [{"name": "Dorm", "price": "$895"}, {"name": "Triple", "price": "$1,095"}, {"name": "Double", "price": "$1,395"}, {"name": "Single", "price": "$1,995"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.secure.retreat.guru/program/somatic-retreat-costa-rica-colynn-cespedes/?form=1&lang=en"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p>You\u2019ve been holding it together for so long. The exhaustion in your body isn\u2019t weakness. It\u2019s a message you haven\u2019t had space to hear.</p><p>Regulate is a body-based retreat rooted in somatic experiencing, nervous system science, and yoga as a real-life practice.</p><p>Not a bootcamp. Not a detox. A gentle, trauma-informed space where slowness is medicine and your body\u2019s signals are finally worth listening to.</p><p>You\u2019ll leave with a deeper understanding of your own nervous system, practical tools for regulation in real life, and a body that remembers what safety feels like.</p><p>No prior experience required. Just a willingness to come home to yourself.</p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "PACKAGE PRICE: For all 4 workshops", "price": "$150"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Relating: Building Relationship with Self, Body, and Nervous System</h3><p><em>90-minute workshop</em></p><p>Before we can regulate, we have to relate. This opening workshop explores how the stories we carry live in the body as physical sensation and emotion. You&#8217;ll develop the language of interoception, learning to notice what is happening before trying to change it. A powerful foundation for everything that follows. This Workshop is 90 minutes. Price is $40.</p><h3>Releasing: Moving Emotion Through the Body</h3><p><em>90-minute workshop</em></p><p>This experiential workshop is a dynamic somatic meditation, adapted through a trauma-informed, choice-based lens. Using movement, breath, sound, and stillness, we create space for the safe discharge of stored stress and emotional energy. This isn&#8217;t about forcing catharsis. It&#8217;s about learning to trust your body&#8217;s capacity to complete what was once interrupted. This Workshop is 90 minutes. Price is $40.</p><h3>Regulation: Boundaries, Capacity, and Emotional Intelligence</h3><p><em>90-minute workshop</em></p><p>Awareness without application only takes us so far. In this coaching-focused workshop, we bring somatic concepts into everyday life, exploring boundaries not as walls or rules, but as nervous system skills. You&#8217;ll learn to recognise your body&#8217;s signals of yes, no, and enough, and begin building a more regulated relationship with your energy and time. This Workshop is 90 minutes. Price is $40.</p><h3>Reverence: Integration, Ceremony, and Celebration</h3><p><em>120-minute workshop</em></p><p>We close with a cacao ceremony and integration space, a time to honour the work you&#8217;ve done, the body that carried you here, and the community you&#8217;ve built. This final workshop is less about learning and more about landing. Softening, opening, and marking the journey with presence, pleasure, and connection. This Workshop is 2 hours. Price is $50.</p><h3>PACKAGE PRICE: For all 4 workshops</h3><p><em>$150</em></p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/ee6afaac-3f31-42b9-a5d4-feea52aa96e4/gallery/hero-image-82-5d39039d.png", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/ee6afaac-3f31-42b9-a5d4-feea52aa96e4/gallery/lower-deck-yoga-class-cropped-300x300-51700eee.png", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/relax-on-the-pool-deck-at-anamaya-resort-300x300-87bae3ad.jpg", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/cristiane-link-300x300-c44147a2.jpg", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/food-5-300x300-342b7e50.jpg", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/53c43106-46e6-4cb6-ae76-6a59601dd3b4/gallery/colynn-vosburgh-781x800-0dbf91b8.jpg", "alt": "Regulate: A Somatic Experiencing Retreat \u2013 Colynn Cespedes"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Colynn Cespedes", "bio_html": "<p>Colynn Cespedes\u2019 journey from Western medicine to holistic healing is one of resilience, transformation, and deep devotion. Beginning in healthcare in 2000, she worked her way from Home Support Worker to Emergency Room Nurse before pursuing medical school\u2014believing it was her true calling. But alongside her studies, yoga pulled her in a different direction. The contrast was undeniable. Eventually, she made the courageous choice to leave medicine behind and dedicate herself fully to yoga, coaching, and energy work.</p><p>With thousands of hours of training and over a hundred Yoga Teacher Trainings led, Colynn integrates her deep clinical knowledge with ancient yogic wisdom. Her teaching blends anatomy, energy work, and past life regressions with humor, real-life wisdom, and spiritual depth. She believes yoga is a sacred roadmap\u2014postures reconnect us with the body, breath bridges the mind and soul, and slowing down isn\u2019t just something we do\u2014it\u2019s a way of being.</p><p>At <strong>Anamaya</strong>, Colynn\u2019s dynamic morning classes awaken the body and mind, while candlelit Yin and Restorative practices in the evening offer deep release. More than just movement, her classes and workshops guide students to shift their perspective, disentangle from life\u2019s dramas, and embrace true presence.</p><p>Now living a nomadic life, with Costa Rica as her home base, Colynn finds joy in the ocean, jungle, and the people she meets. Whether through yoga, coaching, or healing work, her mission is to help others reconnect\u2014with themselves, their bodies, and the infinite possibilities life has to offer.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/200ea630-644d-4ae8-9e16-d2d008ff4d59/gallery/colynn-vosburgh-781x800-0dbf91b8.jpg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('200ea630-644d-4ae8-9e16-d2d008ff4d59', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = '200ea630-644d-4ae8-9e16-d2d008ff4d59';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/relax-on-the-pool-deck-at-anamaya-resort-300x300-87bae3ad.jpg", "image_alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"html": "<h1 style=\"text-align:center\">The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas</h1><p style=\"text-align:center\">with Leslie Lutsch & Colleen Navas</p>", "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "495ea078-5a61-4ddf-806b-6bb6936202d3", "heading": "Dates & Rates", "manual_dates_text": "Aug 8 - 15, 2026", "manual_tiers": [{"name": "Dorm", "price": "$895"}, {"name": "Triple", "price": "$1,095"}, {"name": "Double", "price": "$1,395"}, {"name": "Single", "price": "$1,995"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p><strong>The Art of Thriving: Energy, Healing & Creation</strong></p><p>&nbsp;</p><h3>Are you ready to do more than just survive?<br>This retreat is your invitation to step out of burnout and into a life where you thrive.</h3><p>&nbsp;</p><h3>Join Leslie Lutsch and Colleen Navas at Anamaya Resort in Costa Rica for a transformational week designed to awaken your energy, heal your spirit, and unlock your creativity.</h3><p>&nbsp;</p><h3>Through chakra-based movement, restorative yoga nidra, sound healing, and hands-on creativity workshops, you\u2019ll release what\u2019s been holding you back and plant the seeds for the future you desire.</h3><p>&nbsp;</p><h3>All of this unfolds in Anamaya\u2019s stunning jungle-ocean setting, with nourishing food, meaningful connections, and space to finally put yourself first.</h3><p>&nbsp;</p><h3><strong>Don\u2019t wait for \u201csomeday.\u201d The time to thrive is now.</strong></h3><p><strong>Reserve your spot today!</strong></p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "THRIVE Workshop", "price": "$35\u2013$60", "note": "90-minute workshop"}, {"name": "Tapping Into Creativity For Emotional Healing", "price": "$60", "note": "90-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>THRIVE Workshop</h3><p><em>90-minute workshop &mdash; $35\u2013$60</em></p><p><b>Transform your Daily Toolbox: Free your Spirit and unleash your creative side in order to THRIVE.</b></p><p>Within this series there will be 2 different sessions scheduled throughout the week. We will travel through the depths of our bodies &#8211; physical, mental, emotional, spiritual, we will touch it all. Overall, we will dive deeper and deeper into our energetic body and see what seeds of intention we can plant into our futures.</p><p>We will move through each chakra, what it looks like, and we will learn to build practices to strengthen and heal our chakras. These grounding and eye-opening workshops introduce the chakra system in a way that feels real, accessible, and deeply supportive.</p><p>Helping you understand how stress, and daily life can impact your energy and sense of self.Through a blend of gentle, intuitive movement, guided meditation, and reflective journaling, you\u2019ll begin to reconnect with your body, rebuild your foundation, and reignite your inner strength.These deeply restorative workshops are designed to help you move from awareness into true energetic healing and alignment.</p><p>You\u2019ll leave with simple, powerful tools you can return to in everyday life&#8230; so you can feel more open, more aligned, and more like yourself again.</p><h3>Tapping Into Creativity For Emotional Healing</h3><p><em>90-minute workshop &mdash; $60</em></p><p>Discover how creative expression can be a powerful tool for emotional healing and personal transformation. In this intimate and inspiring workshop, Colleen Navas shares her personal journey of using jewelry making as a lifeline during a challenging chapter of her life, and invites you to explore your own healing through creativity.</p><p>Through guided journaling and vision boarding, you&#8217;ll tap into your inner wisdom, uncover emotional insights, and begin crafting a visual and written map of your transformation. No artistic experience needed, just a willingness to explore, express, and heal.</p><p><strong>What to Expect:</strong></p><ul><li>A heartfelt story of healing through creativity</li><li>Reflective journaling prompts to unlock emotional clarity</li><li>A hands-on vision boarding session to visualize your path forward</li><li>A safe, supportive space for sharing and connection</li></ul>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/relax-on-the-pool-deck-at-anamaya-resort-300x300-87bae3ad.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/yoga-bonus-300x300-e2ddbe11.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/cristiane-link-300x300-c44147a2.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/food-5-300x300-342b7e50.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/leslie-819x800-e5b2e47a.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/colleen-navas-2ed8b2bf.png", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Leslie Lutsch", "bio_html": "<p>Leslie Lutsch lives in the heart of the Rocky Mountains in Colorado, where her days are shaped by skiing, rafting, climbing, and a deep love for nature. But her greatest passion\u2014and the thread that runs through every part of her life\u2014is yoga.</p><p>Leslie first came to Anamaya over a decade ago as a student, and that journey changed everything. What began as a retreat blossomed into years of dedicated study across Costa Rica, Indonesia, and India, leading her through 200, 300, and 500-hour trainings. She went on to assist her beloved teacher for three years of Yoga Teacher Trainings at Anamaya and eventually to teach her own retreats.</p><p>With more than 10 years of teaching experience\u2014from owning her own studio, to workshops, to even horse yoga\u2014Leslie has seen yoga\u2019s ability to transform lives in countless ways. Her classes weave together movement, philosophy, and spiritual depth, always returning to one truth: the balance of discipline and surrender.</p><p>She believes yoga is not just a practice but a way of living\u2014a daily act of choosing awareness, compassion, and alignment with your dharma. Her philosophy is grounded in the wisdom of the Bhagavad Gita and the belief that through action, discipline, and presence, we can move toward our highest selves.</p><p>Leslie lives by the motto, <em>\u201cLive for the moments that take your breath away.\u201d</em> Her teaching invites you to do the same\u2014to step fully into the present moment, awaken your energy, and discover the magic that unfolds when body, mind, and spirit align.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/leslie-819x800-e5b2e47a.jpg", "ao_person_id": "4c5b6bc5-bacf-439b-9a74-a647dd591e07"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('027a4a94-a39f-4421-9338-878953d743db', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{"responsive_mode": "fixed", "role": "Co-Teacher", "name": "Colleen Navas", "bio_html": "<p>Colleen Navas is a devoted mom of two young boys who recently traded the beaches of San Diego for the mountains of Colorado. While she carries the ocean in her heart, she\u2019s embraced the mountain lifestyle and the vibrant creative energy of her new home.</p><p>A yogi for more than a decade, Colleen\u2019s path was first inspired by her sister Leslie, whose encouragement led her deeper into her practice. Yoga remains a grounding force in her life, helping her return to balance through all of life\u2019s seasons. She\u2019s honored to join Leslie again in Costa Rica, guiding others through this transformational retreat.</p><p>Colleen\u2019s love for creativity blossomed during a difficult chapter in her life, when jewelry making became more than a hobby\u2014it became meditation, healing, and a way to transform pain into beauty. Today, she shares this passion to help others tap into their own creativity, resilience, and emotional renewal.</p><p>Her workshops are about more than artistic expression\u2014they\u2019re an invitation to slow down, connect with your inner wisdom, and discover how creativity can be a powerful tool for healing and transformation.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/colleen-navas-2ed8b2bf.png", "ao_person_id": "826bfee1-f3f7-443e-af29-f5368e22a7b7"}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = '027a4a94-a39f-4421-9338-878953d743db';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/relax-on-the-pool-deck-at-anamaya-resort-300x300-87bae3ad.jpg", "image_alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"html": "<h1 style=\"text-align:center\">The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas</h1><p style=\"text-align:center\">with Leslie Lutsch & Colleen Navas</p>", "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "495ea078-5a61-4ddf-806b-6bb6936202d3", "heading": "Dates & Rates", "manual_dates_text": "Aug 8 - 15, 2026", "manual_tiers": [{"name": "Dorm", "price": "$895"}, {"name": "Triple", "price": "$1,095"}, {"name": "Double", "price": "$1,395"}, {"name": "Single", "price": "$1,995"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p><strong>The Art of Thriving: Energy, Healing & Creation</strong></p><p>&nbsp;</p><h3>Are you ready to do more than just survive?<br>This retreat is your invitation to step out of burnout and into a life where you thrive.</h3><p>&nbsp;</p><h3>Join Leslie Lutsch and Colleen Navas at Anamaya Resort in Costa Rica for a transformational week designed to awaken your energy, heal your spirit, and unlock your creativity.</h3><p>&nbsp;</p><h3>Through chakra-based movement, restorative yoga nidra, sound healing, and hands-on creativity workshops, you\u2019ll release what\u2019s been holding you back and plant the seeds for the future you desire.</h3><p>&nbsp;</p><h3>All of this unfolds in Anamaya\u2019s stunning jungle-ocean setting, with nourishing food, meaningful connections, and space to finally put yourself first.</h3><p>&nbsp;</p><h3><strong>Don\u2019t wait for \u201csomeday.\u201d The time to thrive is now.</strong></h3><p><strong>Reserve your spot today!</strong></p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "THRIVE Workshop", "price": "$35\u2013$60", "note": "90-minute workshop"}, {"name": "Tapping Into Creativity For Emotional Healing", "price": "$60", "note": "90-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>THRIVE Workshop</h3><p><em>90-minute workshop &mdash; $35\u2013$60</em></p><p><b>Transform your Daily Toolbox: Free your Spirit and unleash your creative side in order to THRIVE.</b></p><p>Within this series there will be 2 different sessions scheduled throughout the week. We will travel through the depths of our bodies &#8211; physical, mental, emotional, spiritual, we will touch it all. Overall, we will dive deeper and deeper into our energetic body and see what seeds of intention we can plant into our futures.</p><p>We will move through each chakra, what it looks like, and we will learn to build practices to strengthen and heal our chakras. These grounding and eye-opening workshops introduce the chakra system in a way that feels real, accessible, and deeply supportive.</p><p>Helping you understand how stress, and daily life can impact your energy and sense of self.Through a blend of gentle, intuitive movement, guided meditation, and reflective journaling, you\u2019ll begin to reconnect with your body, rebuild your foundation, and reignite your inner strength.These deeply restorative workshops are designed to help you move from awareness into true energetic healing and alignment.</p><p>You\u2019ll leave with simple, powerful tools you can return to in everyday life&#8230; so you can feel more open, more aligned, and more like yourself again.</p><h3>Tapping Into Creativity For Emotional Healing</h3><p><em>90-minute workshop &mdash; $60</em></p><p>Discover how creative expression can be a powerful tool for emotional healing and personal transformation. In this intimate and inspiring workshop, Colleen Navas shares her personal journey of using jewelry making as a lifeline during a challenging chapter of her life, and invites you to explore your own healing through creativity.</p><p>Through guided journaling and vision boarding, you&#8217;ll tap into your inner wisdom, uncover emotional insights, and begin crafting a visual and written map of your transformation. No artistic experience needed, just a willingness to explore, express, and heal.</p><p><strong>What to Expect:</strong></p><ul><li>A heartfelt story of healing through creativity</li><li>Reflective journaling prompts to unlock emotional clarity</li><li>A hands-on vision boarding session to visualize your path forward</li><li>A safe, supportive space for sharing and connection</li></ul>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/relax-on-the-pool-deck-at-anamaya-resort-300x300-87bae3ad.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/yoga-bonus-300x300-e2ddbe11.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/cristiane-link-300x300-c44147a2.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/food-5-300x300-342b7e50.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/leslie-819x800-e5b2e47a.jpg", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/colleen-navas-2ed8b2bf.png", "alt": "The Art of Thriving \u2013 Leslie Lutsch & Colleen Navas"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Leslie Lutsch", "bio_html": "<p>Leslie Lutsch lives in the heart of the Rocky Mountains in Colorado, where her days are shaped by skiing, rafting, climbing, and a deep love for nature. But her greatest passion\u2014and the thread that runs through every part of her life\u2014is yoga.</p><p>Leslie first came to Anamaya over a decade ago as a student, and that journey changed everything. What began as a retreat blossomed into years of dedicated study across Costa Rica, Indonesia, and India, leading her through 200, 300, and 500-hour trainings. She went on to assist her beloved teacher for three years of Yoga Teacher Trainings at Anamaya and eventually to teach her own retreats.</p><p>With more than 10 years of teaching experience\u2014from owning her own studio, to workshops, to even horse yoga\u2014Leslie has seen yoga\u2019s ability to transform lives in countless ways. Her classes weave together movement, philosophy, and spiritual depth, always returning to one truth: the balance of discipline and surrender.</p><p>She believes yoga is not just a practice but a way of living\u2014a daily act of choosing awareness, compassion, and alignment with your dharma. Her philosophy is grounded in the wisdom of the Bhagavad Gita and the belief that through action, discipline, and presence, we can move toward our highest selves.</p><p>Leslie lives by the motto, <em>\u201cLive for the moments that take your breath away.\u201d</em> Her teaching invites you to do the same\u2014to step fully into the present moment, awaken your energy, and discover the magic that unfolds when body, mind, and spirit align.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/leslie-819x800-e5b2e47a.jpg", "ao_person_id": "4c5b6bc5-bacf-439b-9a74-a647dd591e07"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{"responsive_mode": "fixed", "role": "Co-Teacher", "name": "Colleen Navas", "bio_html": "<p>Colleen Navas is a devoted mom of two young boys who recently traded the beaches of San Diego for the mountains of Colorado. While she carries the ocean in her heart, she\u2019s embraced the mountain lifestyle and the vibrant creative energy of her new home.</p><p>A yogi for more than a decade, Colleen\u2019s path was first inspired by her sister Leslie, whose encouragement led her deeper into her practice. Yoga remains a grounding force in her life, helping her return to balance through all of life\u2019s seasons. She\u2019s honored to join Leslie again in Costa Rica, guiding others through this transformational retreat.</p><p>Colleen\u2019s love for creativity blossomed during a difficult chapter in her life, when jewelry making became more than a hobby\u2014it became meditation, healing, and a way to transform pain into beauty. Today, she shares this passion to help others tap into their own creativity, resilience, and emotional renewal.</p><p>Her workshops are about more than artistic expression\u2014they\u2019re an invitation to slow down, connect with your inner wisdom, and discover how creativity can be a powerful tool for healing and transformation.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/colleen-navas-2ed8b2bf.png", "ao_person_id": "826bfee1-f3f7-443e-af29-f5368e22a7b7"}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = 'd94f2f3e-b65a-4f8e-9fb4-bf7ef0ab4fc5';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/hero-image-53-4cffdffa.png", "image_alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"html": "<h1 style=\"text-align:center\">The Anatomy of Sacred Breath \u2013 Cristiane Machado</h1><p style=\"text-align:center\">with Cristiane Machado</p>", "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "61c60017-8ba9-485f-8a7f-7a5b92666466", "heading": "Dates & Rates", "manual_dates_text": "May 16 - 23, 2026", "manual_tiers": [{"name": "Dorm", "price": "$895"}, {"name": "Triple", "price": "$1,095"}, {"name": "Double", "price": "$1,395"}, {"name": "Single", "price": "$1,995"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p>If you\u2019ve been craving a transformational experience that reconnects you to your power, your body, and your spirit, the <em>Anatomy of Sacred Breath Retreat</em> at Anamaya is exactly what you\u2019ve been waiting for.</p><p>Led by one of our most beloved teachers, Cristiane Machado, this retreat is a powerful invitation to come home to yourself.</p><p>With Cristiane\u2019s intuitive guidance and deeply healing workshops \u2013 you\u2019ll move through emotional blocks and step into clarity, confidence, and joy.</p><p>Whether it\u2019s your first time at Anamaya or your first retreat ever, this week will nourish your soul and help you break through what\u2019s been holding you back.</p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "The Essence of Sacred Breath Workshop", "price": "$135", "note": "120-minute workshop"}, {"name": "Cacao Ceremony", "price": "$50", "note": "60-minute workshop"}, {"name": "Z-Fit Movement Workshop", "price": "$15", "note": "60-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>The Essence of Sacred Breath Workshop</h3><p><em>120-minute workshop &mdash; $135</em></p><p>Your breath is more than a life force \u2013 it is a gateway to presence, peace, and transformation. In this workshop, you\u2019ll learn to cultivate mindfulness through each inhale and exhale, embracing the sacred rhythm that connects you to yourself and the world around you.</p><p>Through <em>The Anatomy of Sacred Breath</em>, you\u2019ll uncover practices that calm the mind, nurture inner tranquility, and awaken a deeper sense of authenticity. As you surrender to the flow of breath, you may feel lifted, renewed, and more aligned with your true self.</p><h3>Cacao Ceremony</h3><p><em>60-minute workshop &mdash; $50</em></p><p>Cacao has long been cherished as the \u201cFood of the Gods,\u201d a sacred plant medicine used for centuries to open the heart, awaken joy, and restore balance. Rich in antioxidants, minerals, and the bliss-boosting compound anandamide, cacao is both nourishing for the body and expansive for the spirit.</p><p>In this ceremony, guided by Cristiane Machado, you\u2019ll be welcomed with a ritual cleansing before receiving cacao prepared and blessed in the Mayan tradition. Once the cacao is shared, Cristiane will lead you through a meditation that helps align mind, voice, and heart, creating space for deep connection and self-discovery.</p><p>Every experience is unique \u2013 some feel waves of emotion and release, others a sense of joy, liberation, or heightened clarity. Many describe it as a journey inward, one that leaves them lighter, more open, and deeply connected to themselves.</p><p>This is more than just drinking chocolate \u2013 it\u2019s an invitation to explore the magic of cacao as a doorway to healing, connection, and bliss.</p><h3>Z-Fit Movement Workshop</h3><p><em>60-minute workshop &mdash; $15</em></p><p>Get ready to move, laugh, and let go in this one-of-a-kind class designed to unlock the hips and free the body through self-expression.</p><p>With energizing international music and simple, inviting moves, Z-Fit is for everyone \u2013 even if you\u2019ve never considered yourself a dancer. It\u2019s less about performance and more about joy, connection, and feeling good in your own skin.</p><p>This isn\u2019t your typical workout. It\u2019s a celebration of movement that feels playful, easy, and deeply freeing. Come exactly as you are, meet yourself on the dance floor, and discover how good it feels to love the body you\u2019re in.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/hero-image-53-4cffdffa.png", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/retreat-on-pool-edge-1200px-300x300-a16df9ae.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/yoga_mg_2881-800x600-1-300x300-31d7e222.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/b625eaa2-a2e9-456e-81dd-1a69d4c6a623/gallery/img_5352-300x300-f024c432.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/psx_20200926_135655-300x300-3a0c7299.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/cristiane-machado-headshot-anamaya-6a949530.png", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Cristiane Machado", "bio_html": "<p>Cristiane Machado, a Brazilian-born citizen of the Universe, is a passionate advocate for reconnecting with our divine essence and collective consciousness through therapeutic tools. After moving to the USA in 1999 and attending the Florida School of Massage, Cristiane embarked on a transformative journey that deepened her connection to energy work, yoga, and meditation\u2014practices that reignited her spiritual awakening.</p><p>A dreamer at heart, Cristiane envisions a world of equality and community, where everyone is valued beyond societal labels. As a bodyworker, 200-hour yoga guide specializing in Hatha Yoga, and facilitator of well-being, she creates safe spaces for growth and transformation. Cristiane\u2019s journey led her to Montezuma, Costa Rica, where she continues to guide others in reawakening their divinity through yoga retreats, sacred cacao circles, and her YogaLoka Project.</p><p>Cristiane\u2019s teaching philosophy centers on Yoga as a lifelong practice, a path to self-knowledge, acceptance, and inner peace. She believes in the power of connecting breath, physical effort, and observation to achieve well-being and heal old patterns. Her inclusive teaching style blends Hatha, Yin, and laughing yoga, making the practice accessible to all. Cristiane\u2019s greatest joy is helping her students take their yoga practice off the mat and into the world, fostering kindness and connection.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d0022fca-e2ae-4c01-9f11-76f36b0e122b/gallery/cristiane-machado-headshot-anamaya-6a949530.png", "ao_person_id": "ee6e48a8-2116-45ea-9b6c-a7f344e10bd7"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d0022fca-e2ae-4c01-9f11-76f36b0e122b', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = 'd0022fca-e2ae-4c01-9f11-76f36b0e122b';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/hero-image-53-4cffdffa.png", "image_alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"html": "<h1 style=\"text-align:center\">The Anatomy of Sacred Breath \u2013 Cristiane Machado</h1><p style=\"text-align:center\">with Cristiane Machado</p>", "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "61c60017-8ba9-485f-8a7f-7a5b92666466", "heading": "Dates & Rates", "manual_dates_text": "May 16 - 23, 2026", "manual_tiers": [{"name": "Dorm", "price": "$895"}, {"name": "Triple", "price": "$1,095"}, {"name": "Double", "price": "$1,395"}, {"name": "Single", "price": "$1,995"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p>If you\u2019ve been craving a transformational experience that reconnects you to your power, your body, and your spirit, the <em>Anatomy of Sacred Breath Retreat</em> at Anamaya is exactly what you\u2019ve been waiting for.</p><p>Led by one of our most beloved teachers, Cristiane Machado, this retreat is a powerful invitation to come home to yourself.</p><p>With Cristiane\u2019s intuitive guidance and deeply healing workshops \u2013 you\u2019ll move through emotional blocks and step into clarity, confidence, and joy.</p><p>Whether it\u2019s your first time at Anamaya or your first retreat ever, this week will nourish your soul and help you break through what\u2019s been holding you back.</p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "The Essence of Sacred Breath Workshop", "price": "$135", "note": "120-minute workshop"}, {"name": "Cacao Ceremony", "price": "$50", "note": "60-minute workshop"}, {"name": "Z-Fit Movement Workshop", "price": "$15", "note": "60-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>The Essence of Sacred Breath Workshop</h3><p><em>120-minute workshop &mdash; $135</em></p><p>Your breath is more than a life force \u2013 it is a gateway to presence, peace, and transformation. In this workshop, you\u2019ll learn to cultivate mindfulness through each inhale and exhale, embracing the sacred rhythm that connects you to yourself and the world around you.</p><p>Through <em>The Anatomy of Sacred Breath</em>, you\u2019ll uncover practices that calm the mind, nurture inner tranquility, and awaken a deeper sense of authenticity. As you surrender to the flow of breath, you may feel lifted, renewed, and more aligned with your true self.</p><h3>Cacao Ceremony</h3><p><em>60-minute workshop &mdash; $50</em></p><p>Cacao has long been cherished as the \u201cFood of the Gods,\u201d a sacred plant medicine used for centuries to open the heart, awaken joy, and restore balance. Rich in antioxidants, minerals, and the bliss-boosting compound anandamide, cacao is both nourishing for the body and expansive for the spirit.</p><p>In this ceremony, guided by Cristiane Machado, you\u2019ll be welcomed with a ritual cleansing before receiving cacao prepared and blessed in the Mayan tradition. Once the cacao is shared, Cristiane will lead you through a meditation that helps align mind, voice, and heart, creating space for deep connection and self-discovery.</p><p>Every experience is unique \u2013 some feel waves of emotion and release, others a sense of joy, liberation, or heightened clarity. Many describe it as a journey inward, one that leaves them lighter, more open, and deeply connected to themselves.</p><p>This is more than just drinking chocolate \u2013 it\u2019s an invitation to explore the magic of cacao as a doorway to healing, connection, and bliss.</p><h3>Z-Fit Movement Workshop</h3><p><em>60-minute workshop &mdash; $15</em></p><p>Get ready to move, laugh, and let go in this one-of-a-kind class designed to unlock the hips and free the body through self-expression.</p><p>With energizing international music and simple, inviting moves, Z-Fit is for everyone \u2013 even if you\u2019ve never considered yourself a dancer. It\u2019s less about performance and more about joy, connection, and feeling good in your own skin.</p><p>This isn\u2019t your typical workout. It\u2019s a celebration of movement that feels playful, easy, and deeply freeing. Come exactly as you are, meet yourself on the dance floor, and discover how good it feels to love the body you\u2019re in.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/hero-image-53-4cffdffa.png", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/retreat-on-pool-edge-1200px-300x300-a16df9ae.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/yoga_mg_2881-800x600-1-300x300-31d7e222.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/b625eaa2-a2e9-456e-81dd-1a69d4c6a623/gallery/img_5352-300x300-f024c432.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/psx_20200926_135655-300x300-3a0c7299.jpg", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/cristiane-machado-headshot-anamaya-6a949530.png", "alt": "The Anatomy of Sacred Breath \u2013 Cristiane Machado"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Cristiane Machado", "bio_html": "<p>Cristiane Machado, a Brazilian-born citizen of the Universe, is a passionate advocate for reconnecting with our divine essence and collective consciousness through therapeutic tools. After moving to the USA in 1999 and attending the Florida School of Massage, Cristiane embarked on a transformative journey that deepened her connection to energy work, yoga, and meditation\u2014practices that reignited her spiritual awakening.</p><p>A dreamer at heart, Cristiane envisions a world of equality and community, where everyone is valued beyond societal labels. As a bodyworker, 200-hour yoga guide specializing in Hatha Yoga, and facilitator of well-being, she creates safe spaces for growth and transformation. Cristiane\u2019s journey led her to Montezuma, Costa Rica, where she continues to guide others in reawakening their divinity through yoga retreats, sacred cacao circles, and her YogaLoka Project.</p><p>Cristiane\u2019s teaching philosophy centers on Yoga as a lifelong practice, a path to self-knowledge, acceptance, and inner peace. She believes in the power of connecting breath, physical effort, and observation to achieve well-being and heal old patterns. Her inclusive teaching style blends Hatha, Yin, and laughing yoga, making the practice accessible to all. Cristiane\u2019s greatest joy is helping her students take their yoga practice off the mat and into the world, fostering kindness and connection.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d0022fca-e2ae-4c01-9f11-76f36b0e122b/gallery/cristiane-machado-headshot-anamaya-6a949530.png", "ao_person_id": "ee6e48a8-2116-45ea-9b6c-a7f344e10bd7"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('d6e8e73e-71a9-4e07-89c1-802d892b4954', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = 'd6e8e73e-71a9-4e07-89c1-802d892b4954';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/hero-image-65-cd65e9db.png", "image_alt": "Awaken Your Path \u2013 Missy & David Hartley", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"html": "<h1 style=\"text-align:center\">Awaken Your Path \u2013 Missy & David Hartley</h1><p style=\"text-align:center\">with Missy Hartley & David Hartley</p>", "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "2553f262-0112-4591-aace-a080083bd3d7", "heading": "Dates & Rates", "manual_dates_text": "June 27 - July 4, 2026", "manual_tiers": [{"name": "Dorm", "price": "$895"}, {"name": "Triple", "price": "$1,095"}, {"name": "Double", "price": "$1,395"}, {"name": "Single", "price": "$1,995"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p>You have been taking care of everything and everyone. What about you?</p><h3>Missy and David hold space for every part of you that has been waiting for attention. Your body, your relationships, your sense of self, and the patterns quietly running your life.</h3><p>Their yoga, sound healing, partner practices, and workshops are invitations, not obligations.</p><p>Come solo or bring someone you love. Leave knowing yourself more deeply.</p><p><b>Design Your Perfect Week: </b>Your retreat, your way. Join yoga classes, book spa treatments, explore adventures&#8230; or do nothing but rest by the pool. Everything is optional and paid at checkout, so you can decide what feels right each day.</p><p>Discover renewal and transformation at Anamaya in Montezuma, Costa Rica.</p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Connection & Mutual Awakening", "price": "$25", "note": "90-minute workshop"}, {"name": "Awaken Your Path, Sound Bath", "price": "$40", "note": "75-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Connection & Mutual Awakening</h3><p><em>90-minute workshop &mdash; $25</em></p><p><strong>Partner Yoga + Trust & Communication</strong></p><p>A gentle partner yoga session for couples or solo participants (we\u2019ll pair you if you come alone). In our tech-filled world of smartphones and screens, learning to truly connect with others matters more than ever. Partner yoga strengthens relationships, marriages, and friendships while teaching skills to form deeper bonds even with strangers. Through supported poses, gentle assists, synchronized breathing, and trust-building movements, you\u2019ll find balance, let go of control, and deepen presence together.</p><h3>Awaken Your Path, Sound Bath</h3><p><em>75-minute workshop &mdash; $40</em></p><p><strong>Deep Relaxation & Vibrational Healing</strong></p><p>A deeply immersive sound bath using crystal bowls, chimes, voice, and nature sounds to release tension, calm the nervous system, clear inner blocks, and bring fresh clarity to your awakened journey.</p><h3>Roam Free: Travel the World, Do What You Love</h3><p><strong>Pursue Your Passion & Be Financially Free</strong></p><p>Imagine travelling the globe on your terms, pursuing your passions, waking up in new places and working (or not working) exactly how you want \u2013 while money flows with ease instead of stress. This empowering workshop shows you how to achieve true financial independence for a location-independent life. Blending practical steps like building remote income streams, smart tax strategies, mindful money habits, and yogic principles of ease and surrender, you\u2019ll gain actionable tools, mindset shifts, and inspiration to make world-roaming freedom your reality. No more waiting for \u201csomeday.\u201d Start designing your nomadic passion-fueled life today.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/hero-image-65-cd65e9db.png", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/relax-on-the-pool-deck-at-anamaya-resort-300x300-87bae3ad.jpg", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/yoga-bonus-300x300-e2ddbe11.jpg", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/infrared-sauna-at-anamaya-resort-300x300-4b2c7354.png", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/cristiane-link-300x300-c44147a2.jpg", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/food-5-300x300-342b7e50.jpg", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/missy-hartley-headshot-6f60b371.png", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/david-hartley-headshot-e601bded.png", "alt": "Awaken Your Path \u2013 Missy & David Hartley"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Missy Hartley", "bio_html": "<p>Missy&#8217;s yoga journey began in 2016, a pivotal year that would change her life. It wasn\u2019t until she met her husband David that the magic of yoga truly clicked for her. He introduced her to the mesmerizing Anamaya Resort, nestled in the lush jungles of Costa Rica. As the sun set on her last day there, a fire ignited within her\u2014she knew this was where she belonged. Determined to teach in that paradise, Missy and David immersed themselves in an intensive yoga teacher training at Anamaya, diving deeper into their shared passion for wellness.</p><p>Today, Missy&#8217;s life is a beautiful blend of travel, yoga, and adventure. She\u2019s the proud fur mom of two playful cats and finds joy in hiking the rugged, picturesque mountains of Arizona. But she\u2019s not just a yogi\u2014Missy is also a Financial Assistant at Wealth Wellness, the dynamic firm she co-runs with David. She combines her deep understanding of wellness with financial savvy, guiding clients toward not just wealth, but holistic prosperity.</p><p>In her yoga practice, Missy\u2019s mission is clear: to make yoga accessible to everyone. She shatters the myth that flexibility is a must, creating a welcoming space for students of all shapes, sizes, and abilities. Her classes are more than just a series of poses\u2014they\u2019re an empowering journey, especially for women seeking confidence and strength. Through her own story of self-discovery, Missy inspires her students to embrace their uniqueness, proving that yoga is as much about uplifting the soul as it is about strengthening the body. Whether on the mat or in life, she\u2019s all about finding balance, joy, and transformation.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/missy-hartley-headshot-6f60b371.png"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{"responsive_mode": "fixed", "role": "Co-Teacher", "name": "David Hartley", "bio_html": "<p>David Hartley is a seasoned financial advisor with over two decades of experience, proudly rooted in Michigan and a graduate of Michigan State University. After eight enriching years in Colorado, he now calls Arizona home. Beyond his professional expertise, David has a profound passion for yoga, which he integrates into his financial practice, creating a unique approach that fosters holistic well-being and mindful financial planning.</p><p>David\u2019s journey into yoga began with his first teacher training at Lifetime Fitness, where he developed a strong foundation in the practice. Shortly after his training he went to Anamaya and experienced his full potential, and started manifesting the life he wanted. Returning to Anamaya for a second time was a profoundly meaningful experience for David. This time, he was accompanied by his new wife, Missy, celebrating their honeymoon at the very place where he had experienced such personal transformation. Their shared love for yoga and the serenity of Anamaya marked the beginning of a new chapter in their lives together. The transformative experience not only enriched his personal growth but also inspired him to intertwine the grounding principles of yoga with his financial practice.</p><p>David\u2019s philosophy in both yoga and financial advising is rooted in the belief that true wealth goes beyond monetary success; it encompasses a balanced and fulfilled life. By integrating mindfulness and yoga principles into his financial practice, he empowers his clients to achieve clarity and purpose, aligning their financial goals with their personal values and well-being. David is honored to teach at Anamaya and to bring his teachings to the same place that gave him so much wisdom.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34/gallery/david-hartley-headshot-e601bded.png"}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = 'a19ea53e-8606-4dfd-a9f2-8cce7c4c3b34';
