-- ============================================================
-- 0080: Convert 3 more real retreat pages (newly extracted after
-- Geoff signed in to unblock the pages that required login).
-- The Art of Being has a real gallery (6 images) and real hero.
-- Explore and Restore + Spark Your Life had NO images at all on
-- the legacy WP page, so those two get NO hero/gallery override
-- and inherit the shared master's generic placeholder image.
-- None of the 3 have an AnamayOS leader_person_id yet, so leader
-- cards use manual bio/photo (same as first batch of 5).
-- Spark Your Life has no Retreat Guru registration link yet, so
-- its CTA falls back to the booking-calendar page.
-- ============================================================

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/retreat-on-pool-edge-1200px-300x300-a16df9ae.jpg", "image_alt": "The Art of Being \u2013 Natalia Chaverri", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"retreat_id": "8d2a4aac-c5e0-4127-893b-3fe2ee940197", "manual_title": "The Art of Being \u2013 Natalia Chaverri"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "8d2a4aac-c5e0-4127-893b-3fe2ee940197", "heading": "Dates & Rates", "manual_dates_text": "Oct 11 - 18, 2025", "manual_tiers": [{"name": "Dorm", "price": "$795"}, {"name": "Triple", "price": "$945"}, {"name": "Double", "price": "$1,095"}, {"name": "Single", "price": "$1,645"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.secure.retreat.guru/program/the-art-of-being-retreat-natalia-chaverri-2/?form=1&lang=en"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p><strong>The Art of Being: A Retreat For Those Ready to Thrive.</strong></p><p>Discover the transformative power of choosing yourself at this Costa Rica retreat.</p><p>In a world that demands constant doing, \u201cThe Art of Being\u201d invites you to remember who you are beneath it all. Design your perfect escape with yoga, mindful workshops, spa treatments, nature adventures, or pure relaxation\u2026 this is your moment to reconnect with what truly matters.</p><p>When you give yourself permission to just BE, everything shifts. Your personalized retreat experience awaits in paradise.</p><p>Anamaya provides the perfect escape to reconnect with yourself while stepping away from life\u2019s relentless pace and urban chaos. Throughout the week, Natalia will guide you through carefully curated workshops designed for souls ready to break free from limiting routines and rediscover what truly matters.</p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Partner Yoga Workshop", "price": "$90", "note": "90-minute workshop"}, {"name": "Bio-Creation Workshop", "price": "$90", "note": "90-minute workshop"}, {"name": "Awakening the Senses Workshop", "price": "$90", "note": "90-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Partner Yoga Workshop</h3><p><em>90-minute workshop &mdash; $90</em></p><p>There&#8217;s something magical about sharing your practice with another person. In this playful workshop, you&#8217;ll flow through sequences designed for two, discovering new depths in familiar poses while building trust and connection. Expect laughter, supported stretches, creative balances, and those beautiful moments when two people move as one. As they say, <em>&#8220;Unity is strength&#8221;</em> \u2013 and you&#8217;ll feel that power firsthand.</p><h3>Bio-Creation Workshop</h3><p><em>90-minute workshop &mdash; $90</em></p><p>Bio-creation is the art of connecting with your highest self and letting your inner potential shine. Grounded in earth energy yet reaching toward infinite possibility, we&#8217;ll dive deep into your soul&#8217;s true desires and create a roadmap for the life you&#8217;ve been dreaming of. Through intentional practices, you&#8217;ll learn to shift your emotional frequency toward joy, abundance, and wellness while releasing old patterns that no longer serve you. Discover the essence of who you truly are and remember this truth: a peaceful mind is a powerful mind.</p><h3>Awakening the Senses Workshop</h3><p><em>90-minute workshop &mdash; $90</em></p><p>Take an extraordinary journey inward as we awaken your inner light through the gateway of the senses. Through mindful experiences with food, music, movement, essential oils, and sacred silence, you&#8217;ll rediscover the profound connection between your senses and your soul. This immersive meditation becomes a conscious celebration of life itself, bringing you fully into the magic of the present moment and the vibrant being you truly are.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/retreat-on-pool-edge-1200px-300x300-a16df9ae.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/yoga_mg_2881-800x600-1-300x300-31d7e222.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/bf86e721-1ef4-4586-b22c-a030b04ddc15/gallery/anamaya-guests-on-the-beach-300x300-bba25b6e.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/psx_20200926_135655-300x300-3a0c7299.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/bf86e721-1ef4-4586-b22c-a030b04ddc15/gallery/foto-nati--800x800-2f791b4a.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Natalia Chaverri", "bio_html": "<p>Meet Natalia, your transformational guide for \u201cThe Art of Being\u201d retreat in Costa Rica. A devoted healer with over 25 years of experience, this passionate Costa Rican has dedicated her life to the mysteries of well-being and the beauty of holistic healing.</p><p>Beginning her journey at just 16, Natalia became a certified Holistic Balance Instructor and Yoga Teacher at the renowned GAIA Holistic Institute in San Jos\u00e9. Her extensive training spans Hatha Yoga, meditation, sound healing, Reiki, Biocreation, reflexology, and holistic massage. She later deepened her practice through 300-hour Hatha Yoga and 200-hour Anusara Yoga teacher trainings with international instructors.</p><p>Natalia''s true calling emerged in 2005 when she discovered aquatic bodywork. As a certified Watsu\u00ae and Aquadinamic Instructor, she founded Watsu\u00ae Costa Rica and the Aquatic Therapy Institute of Costa Rica, becoming a pioneer in water-based healing throughout Central America.</p><p>Her global studies have taken her from Thailand (Thai massage and Chi Nei Tsang) to Bali (yoga immersion), while her Master\u2019s degree in Therapeutic Exercise from Barcelona perfectly blends her physical therapy background with yoga and somatic movement.</p><p>At Anamaya Resort, Natalia has guided over nine transformational retreats, offering yoga, meditation, partner yoga, sound healing, Biocreation, and her signature \u201cAwakening the Senses\u201d workshop. This global soul divides her time between Costa Rica and Spain, continuously learning from diverse cultures and sharing her gifts with love, joy, and presence.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/bf86e721-1ef4-4586-b22c-a030b04ddc15/gallery/foto-nati--800x800-2f791b4a.jpg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('bf86e721-1ef4-4586-b22c-a030b04ddc15', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = 'bf86e721-1ef4-4586-b22c-a030b04ddc15';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', '144dbbd6-df8a-4bfe-9445-fa8abdc04278', '{"image_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/retreat-on-pool-edge-1200px-300x300-a16df9ae.jpg", "image_alt": "The Art of Being \u2013 Natalia Chaverri", "image_fit": "cover", "height_px": 560, "overlay_opacity": 0, "align": "center", "corner_radius_px": 8}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"retreat_id": "8d2a4aac-c5e0-4127-893b-3fe2ee940197", "manual_title": "The Art of Being \u2013 Natalia Chaverri"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "8d2a4aac-c5e0-4127-893b-3fe2ee940197", "heading": "Dates & Rates", "manual_dates_text": "Oct 11 - 18, 2025", "manual_tiers": [{"name": "Dorm", "price": "$795"}, {"name": "Triple", "price": "$945"}, {"name": "Double", "price": "$1,095"}, {"name": "Single", "price": "$1,645"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.secure.retreat.guru/program/the-art-of-being-retreat-natalia-chaverri-2/?form=1&lang=en"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p><strong>The Art of Being: A Retreat For Those Ready to Thrive.</strong></p><p>Discover the transformative power of choosing yourself at this Costa Rica retreat.</p><p>In a world that demands constant doing, \u201cThe Art of Being\u201d invites you to remember who you are beneath it all. Design your perfect escape with yoga, mindful workshops, spa treatments, nature adventures, or pure relaxation\u2026 this is your moment to reconnect with what truly matters.</p><p>When you give yourself permission to just BE, everything shifts. Your personalized retreat experience awaits in paradise.</p><p>Anamaya provides the perfect escape to reconnect with yourself while stepping away from life\u2019s relentless pace and urban chaos. Throughout the week, Natalia will guide you through carefully curated workshops designed for souls ready to break free from limiting routines and rediscover what truly matters.</p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Partner Yoga Workshop", "price": "$90", "note": "90-minute workshop"}, {"name": "Bio-Creation Workshop", "price": "$90", "note": "90-minute workshop"}, {"name": "Awakening the Senses Workshop", "price": "$90", "note": "90-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Partner Yoga Workshop</h3><p><em>90-minute workshop &mdash; $90</em></p><p>There&#8217;s something magical about sharing your practice with another person. In this playful workshop, you&#8217;ll flow through sequences designed for two, discovering new depths in familiar poses while building trust and connection. Expect laughter, supported stretches, creative balances, and those beautiful moments when two people move as one. As they say, <em>&#8220;Unity is strength&#8221;</em> \u2013 and you&#8217;ll feel that power firsthand.</p><h3>Bio-Creation Workshop</h3><p><em>90-minute workshop &mdash; $90</em></p><p>Bio-creation is the art of connecting with your highest self and letting your inner potential shine. Grounded in earth energy yet reaching toward infinite possibility, we&#8217;ll dive deep into your soul&#8217;s true desires and create a roadmap for the life you&#8217;ve been dreaming of. Through intentional practices, you&#8217;ll learn to shift your emotional frequency toward joy, abundance, and wellness while releasing old patterns that no longer serve you. Discover the essence of who you truly are and remember this truth: a peaceful mind is a powerful mind.</p><h3>Awakening the Senses Workshop</h3><p><em>90-minute workshop &mdash; $90</em></p><p>Take an extraordinary journey inward as we awaken your inner light through the gateway of the senses. Through mindful experiences with food, music, movement, essential oils, and sacred silence, you&#8217;ll rediscover the profound connection between your senses and your soul. This immersive meditation becomes a conscious celebration of life itself, bringing you fully into the magic of the present moment and the vibrant being you truly are.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', 'd384555b-4b04-4acc-8826-de4825a1ec0e', '{"images": [{"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/retreat-on-pool-edge-1200px-300x300-a16df9ae.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/yoga_mg_2881-800x600-1-300x300-31d7e222.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/027a4a94-a39f-4421-9338-878953d743db/gallery/spa-1-300x300-c701562a.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/bf86e721-1ef4-4586-b22c-a030b04ddc15/gallery/anamaya-guests-on-the-beach-300x300-bba25b6e.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/d6e8e73e-71a9-4e07-89c1-802d892b4954/gallery/psx_20200926_135655-300x300-3a0c7299.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}, {"url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/bf86e721-1ef4-4586-b22c-a030b04ddc15/gallery/foto-nati--800x800-2f791b4a.jpg", "alt": "The Art of Being \u2013 Natalia Chaverri"}], "layout": "grid", "columns": 3, "lightbox": true, "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Natalia Chaverri", "bio_html": "<p>Meet Natalia, your transformational guide for \u201cThe Art of Being\u201d retreat in Costa Rica. A devoted healer with over 25 years of experience, this passionate Costa Rican has dedicated her life to the mysteries of well-being and the beauty of holistic healing.</p><p>Beginning her journey at just 16, Natalia became a certified Holistic Balance Instructor and Yoga Teacher at the renowned GAIA Holistic Institute in San Jos\u00e9. Her extensive training spans Hatha Yoga, meditation, sound healing, Reiki, Biocreation, reflexology, and holistic massage. She later deepened her practice through 300-hour Hatha Yoga and 200-hour Anusara Yoga teacher trainings with international instructors.</p><p>Natalia''s true calling emerged in 2005 when she discovered aquatic bodywork. As a certified Watsu\u00ae and Aquadinamic Instructor, she founded Watsu\u00ae Costa Rica and the Aquatic Therapy Institute of Costa Rica, becoming a pioneer in water-based healing throughout Central America.</p><p>Her global studies have taken her from Thailand (Thai massage and Chi Nei Tsang) to Bali (yoga immersion), while her Master\u2019s degree in Therapeutic Exercise from Barcelona perfectly blends her physical therapy background with yoga and somatic movement.</p><p>At Anamaya Resort, Natalia has guided over nine transformational retreats, offering yoga, meditation, partner yoga, sound healing, Biocreation, and her signature \u201cAwakening the Senses\u201d workshop. This global soul divides her time between Costa Rica and Spain, continuously learning from diverse cultures and sharing her gifts with love, joy, and presence.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-media/staging/bf86e721-1ef4-4586-b22c-a030b04ddc15/gallery/foto-nati--800x800-2f791b4a.jpg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('1f1a97b2-0d76-44f8-ad47-0396af07d57a', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = '1f1a97b2-0d76-44f8-ad47-0396af07d57a';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"retreat_id": "7d801a00-0851-475f-ad97-71bb7b75f86a", "manual_title": "Pura Vida Haven Retreat \u2013 Kimberly Manthey"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "7d801a00-0851-475f-ad97-71bb7b75f86a", "heading": "Dates & Rates", "manual_dates_text": "March 6 - 13, 2027", "manual_tiers": [{"name": "Dorm", "price": "$1,095"}, {"name": "Triple", "price": "$1,295"}, {"name": "Double", "price": "$1,595"}, {"name": "Single", "price": "$2,195"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.secure.retreat.guru/program/pura-vida-costa-rica-retreat-kimberly-manthey/?form=1&lang=en"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p>A Retreat for a Much Deserved Reset.</p><p>You keep telling yourself that you\u2019ll take time for YOU \u2013 when the work slows down, when the kids need you less, when life isn\u2019t so demanding. But let\u2019s be real: that <em>someday</em> never comes unless you claim it.</p><p><strong>This is your moment.</strong></p><p>If life has been asking too much of you lately, this retreat offers the pause your nervous system has been craving. With over 25 years of experience and a loyal following at Anamaya, Kimberly will create a haven where you can finally exhale, reflect, and reset.</p><p>This retreat is for anyone who\u2019s been holding it all together and is ready to feel supported, energized, and more like themselves again.</p><p><strong>Come as you are \u2013 and leave feeling Pura Vida.</strong></p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Explore & Restore: A 2-Part Workshop Series to Reclaim Your Energy and Strengthen Your Mental Health", "price": "$90", "note": "60-minute workshop"}, {"name": "Yoga Nidra", "price": "$35", "note": "60-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Explore & Restore: A 2-Part Workshop Series to Reclaim Your Energy and Strengthen Your Mental Health</h3><p><em>60-minute workshop &mdash; $90</em></p><p><strong>Practice self-compassion. Embrace change with clarity. Build the kind of resilience that lasts.</strong></p><p>If you\u2019ve been running on empty, questioning your capacity, or feeling stuck in patterns that drain you, this workshop series is for you.</p><p>Led by Kimberly, these two one-hour workshops blend real-world tools with reflective prompts to help you shift how you show up for yourself, especially when life feels overwhelming.</p><p><strong>You\u2019ll walk away with:</strong></p><ul><li>10 practices that support mental clarity and emotional strength</li><li>7 simple, natural ways to boost your energy\u2014no burnout required</li><li>Tools to stop wasting your time on what doesn\u2019t matter</li><li>A mindset shift that turns setbacks into momentum</li><li>New language for how you speak to yourself and hold your power</li></ul><p>You don\u2019t have to attend both sessions, but each one offers a different layer of insight and support. Show up to one or both, and leave with practical strategies and a clearer head.</p><p><strong>Come as you are. Leave with a lighter load and a stronger sense of self.</strong></p><h3>Yoga Nidra</h3><p><em>60-minute workshop &mdash; $35</em></p><p>Yoga nidra, also known as yogic sleep, is a guided meditation practice that induces a state of consciousness between waking and sleeping. It&#8217;s a powerful tool for deep relaxation, stress reduction, and improved sleep quality.</p><p>During a yoga nidra session, you will lie in Savasana (corpse pose) and follow a series of guided instructions that lead you through various stages of awareness and relaxation.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Kimberly Manthey", "bio_html": "<p>Kimberly Manthey, founder of Dirty Feet Yoga and Wellness has been instructing yoga teachers and everyday people for over 25 years. Pulling from multiple styles of Yoga, Kimberly\u2019s mission is to bring together the body, mind, and spirit each and every time she crosses your path.</p><p>She began yoga in 1997 as a means of stress reduction when her high powered corporate career, grief over the death of her father, and a brand new marriage all collided and caused her to re-evaluate her purpose.</p><p>In addition to leading several yoga retreats nationwide, and internationally, she has coached corporate sales teams, schools, and hundreds of individuals, and brings with her, a unique blend of humor and story telling. Comfortable instructing to all levels of yoga, her classes can range from gentle and soothing to powerful and dynamic.</p><p>She looks forward to meeting you wherever you are on your journey in life. Namaste!</p><h3>Certifications &amp; Qualifications</h3><ul><li>Experienced Registered Yoga Teacher with the Yoga Alliance</li><li>Continuing Education Provider with Yoga Alliance</li><li>Certified Advanced Yoga and Meditation Teacher</li><li>Certified Wellness Coach through the International Association of Wellness Professionals</li><li>Over 25 years of hands-on teaching experience.</li></ul>"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('4f8f87ac-cc57-436c-ac07-e230bbcf957b', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = '4f8f87ac-cc57-436c-ac07-e230bbcf957b';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"retreat_id": "7d801a00-0851-475f-ad97-71bb7b75f86a", "manual_title": "Pura Vida Haven Retreat \u2013 Kimberly Manthey"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "7d801a00-0851-475f-ad97-71bb7b75f86a", "heading": "Dates & Rates", "manual_dates_text": "March 6 - 13, 2027", "manual_tiers": [{"name": "Dorm", "price": "$1,095"}, {"name": "Triple", "price": "$1,295"}, {"name": "Double", "price": "$1,595"}, {"name": "Single", "price": "$2,195"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.secure.retreat.guru/program/pura-vida-costa-rica-retreat-kimberly-manthey/?form=1&lang=en"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p>A Retreat for a Much Deserved Reset.</p><p>You keep telling yourself that you\u2019ll take time for YOU \u2013 when the work slows down, when the kids need you less, when life isn\u2019t so demanding. But let\u2019s be real: that <em>someday</em> never comes unless you claim it.</p><p><strong>This is your moment.</strong></p><p>If life has been asking too much of you lately, this retreat offers the pause your nervous system has been craving. With over 25 years of experience and a loyal following at Anamaya, Kimberly will create a haven where you can finally exhale, reflect, and reset.</p><p>This retreat is for anyone who\u2019s been holding it all together and is ready to feel supported, energized, and more like themselves again.</p><p><strong>Come as you are \u2013 and leave feeling Pura Vida.</strong></p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Explore & Restore: A 2-Part Workshop Series to Reclaim Your Energy and Strengthen Your Mental Health", "price": "$90", "note": "60-minute workshop"}, {"name": "Yoga Nidra", "price": "$35", "note": "60-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Explore & Restore: A 2-Part Workshop Series to Reclaim Your Energy and Strengthen Your Mental Health</h3><p><em>60-minute workshop &mdash; $90</em></p><p><strong>Practice self-compassion. Embrace change with clarity. Build the kind of resilience that lasts.</strong></p><p>If you\u2019ve been running on empty, questioning your capacity, or feeling stuck in patterns that drain you, this workshop series is for you.</p><p>Led by Kimberly, these two one-hour workshops blend real-world tools with reflective prompts to help you shift how you show up for yourself, especially when life feels overwhelming.</p><p><strong>You\u2019ll walk away with:</strong></p><ul><li>10 practices that support mental clarity and emotional strength</li><li>7 simple, natural ways to boost your energy\u2014no burnout required</li><li>Tools to stop wasting your time on what doesn\u2019t matter</li><li>A mindset shift that turns setbacks into momentum</li><li>New language for how you speak to yourself and hold your power</li></ul><p>You don\u2019t have to attend both sessions, but each one offers a different layer of insight and support. Show up to one or both, and leave with practical strategies and a clearer head.</p><p><strong>Come as you are. Leave with a lighter load and a stronger sense of self.</strong></p><h3>Yoga Nidra</h3><p><em>60-minute workshop &mdash; $35</em></p><p>Yoga nidra, also known as yogic sleep, is a guided meditation practice that induces a state of consciousness between waking and sleeping. It&#8217;s a powerful tool for deep relaxation, stress reduction, and improved sleep quality.</p><p>During a yoga nidra session, you will lie in Savasana (corpse pose) and follow a series of guided instructions that lead you through various stages of awareness and relaxation.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Kimberly Manthey", "bio_html": "<p>Kimberly Manthey, founder of Dirty Feet Yoga and Wellness has been instructing yoga teachers and everyday people for over 25 years. Pulling from multiple styles of Yoga, Kimberly\u2019s mission is to bring together the body, mind, and spirit each and every time she crosses your path.</p><p>She began yoga in 1997 as a means of stress reduction when her high powered corporate career, grief over the death of her father, and a brand new marriage all collided and caused her to re-evaluate her purpose.</p><p>In addition to leading several yoga retreats nationwide, and internationally, she has coached corporate sales teams, schools, and hundreds of individuals, and brings with her, a unique blend of humor and story telling. Comfortable instructing to all levels of yoga, her classes can range from gentle and soothing to powerful and dynamic.</p><p>She looks forward to meeting you wherever you are on your journey in life. Namaste!</p><h3>Certifications &amp; Qualifications</h3><ul><li>Experienced Registered Yoga Teacher with the Yoga Alliance</li><li>Continuing Education Provider with Yoga Alliance</li><li>Certified Advanced Yoga and Meditation Teacher</li><li>Certified Wellness Coach through the International Association of Wellness Professionals</li><li>Over 25 years of hands-on teaching experience.</li></ul>"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('316d6f22-e180-49d4-8555-0823d5ff2752', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = '316d6f22-e180-49d4-8555-0823d5ff2752';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"retreat_id": "7a26a594-f77e-448b-8b6c-5b036537f778", "manual_title": "Spark Your Life Retreat \u2013 Dagmar Spremberg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "7a26a594-f77e-448b-8b6c-5b036537f778", "heading": "Dates & Rates", "manual_dates_text": "Jan 30 - Feb 6, 2027", "manual_tiers": [{"name": "Dorm", "price": "$1,095"}, {"name": "Triple", "price": "$1,295"}, {"name": "Double", "price": "$1,595"}, {"name": "Single", "price": "$2,195"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p><strong>You Know That Version of You Who Feels Alive, Clear, and Fully Here?</strong></p><p>They\u2019re not gone \u2013 just buried under everything you\u2019ve been carrying, and this retreat is where you finally set it all down. For one week in Costa Rica, you step out of the noise and back into yourself.</p><p>Dagmar\u2019s dynamic morning vinyasa wakes up what\u2019s been asleep. Her restorative evening yin gives you permission to exhale. And the space in between \u2013 the ocean views, the nourishing food, the jungle air \u2013 does something to a person that\u2019s almost impossible to explain until you\u2019ve felt it.</p><p>This retreat is fully yours to shape. Add spa treatments, Costa Rican adventures, or simply let the days unfold at whatever pace your body is asking for. Your week, your way.</p><p><strong>Leave grounded, energized, and reconnected to the spark that\u2019s been waiting for you.</strong></p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Conscious Communication Workshop", "price": "$70", "note": "90-minute workshop"}, {"name": "Ecstatic Dance Workshop", "price": "$70", "note": "90-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Conscious Communication Workshop</h3><p><em>90-minute workshop &mdash; $70</em></p><p><strong>There&#8217;s a version of every conversation you didn&#8217;t have.</strong></p><p>The thing you almost said. The need you talked yourself out of expressing. The moment you went quiet instead of honest &#8211; not because you didn&#8217;t have the words, but because somewhere along the way you learned it was safer not to use them.</p><p>That habit has a cost. Relationships that stay surface-level. Resentment that builds without a name. A low-grade exhaustion from editing yourself before you even open your mouth.</p><p>This workshop is 90 minutes of unlearning that.</p><p>You&#8217;ll walk away with real, practical tools for saying what you mean with clarity and care &#8211; no over-explaining, no shutdown, no wondering afterward if you handled it wrong. Language for asking for what you need. Tools for staying grounded when conversations get hard. And a clearer picture of where you hold back and why.</p><h3>Ecstatic Dance Workshop</h3><p><em>90-minute workshop &mdash; $70</em></p><p><strong>No steps to learn. No mirrors. No performing.</strong></p><p>Just music, movement, and 90 minutes of full permission to be completely in your body.</p><p>Ecstatic Dance is a movement meditation. The music builds slowly, the thinking quiets, and something underneath all that effort finally gets to breathe. Most people walk in skeptical and leave wondering why they don&#8217;t do this every week.</p><p>You don&#8217;t need to dance well. You don&#8217;t even need to like dancing. You just need to be willing to get out of your head for a little while.</p><p>You&#8217;ll leave lighter, looser, and more at home in yourself than you&#8217;ve felt in a long time.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Dagmar Spremberg", "bio_html": "<p><strong>Reignite Your Inner Spark with Dagmar Spremberg</strong></p><p>Dagmar Spremberg made the kind of leap most people only dream about. She left city life in LA and New York, followed something deeper, and landed in Montezuma, Costa Rica \u2013 where she founded Montezuma Yoga and built a life that actually matched who she was.</p><p>That journey is woven into everything she teaches.</p><p>A 500-hour E-RYT trained in Anusara, Vinyasa Flow, and Yin Yoga, and mentored by master teachers including Elena Brower and Rod Stryker, Dagmar works with the breath as the doorway to intuition and inner knowing. Her morning flows are energizing and accessible. Her evening yin sessions are deeply restorative. Both are open to all levels, and both carry the same quiet message: you already have everything you need. This week is just about remembering it.</p><p>You\u2019ll leave with more than a yoga practice. You\u2019ll leave with the tools to keep showing up for yourself long after you\u2019re back in real life.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-leader-photos/staging/58ba79c2-84ef-4dfe-82b4-e56059112124/leader/49171b107137e9a6f27ad4128395cffb041b5dc9eb0677119b3b659ce06e0457-db55b599.jpg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('58ba79c2-84ef-4dfe-82b4-e56059112124', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = '58ba79c2-84ef-4dfe-82b4-e56059112124';

insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', 'ea266e9c-2980-454b-b1a1-8eab474c3a77', '{"retreat_id": "7a26a594-f77e-448b-8b6c-5b036537f778", "manual_title": "Spark Your Life Retreat \u2013 Dagmar Spremberg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', 'ca30fa78-411b-434c-acfa-0996a9a70fcf', '{"retreat_id": "7a26a594-f77e-448b-8b6c-5b036537f778", "heading": "Dates & Rates", "manual_dates_text": "Jan 30 - Feb 6, 2027", "manual_tiers": [{"name": "Dorm", "price": "$1,095"}, {"name": "Triple", "price": "$1,295"}, {"name": "Double", "price": "$1,595"}, {"name": "Single", "price": "$2,195"}], "manual_cta_label": "Book Now", "manual_cta_href": "https://anamaya.com/rg-calendar/"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', 'c229572b-1c0d-446e-8c7c-f05b2852bb92', '{"html": "<p><strong>You Know That Version of You Who Feels Alive, Clear, and Fully Here?</strong></p><p>They\u2019re not gone \u2013 just buried under everything you\u2019ve been carrying, and this retreat is where you finally set it all down. For one week in Costa Rica, you step out of the noise and back into yourself.</p><p>Dagmar\u2019s dynamic morning vinyasa wakes up what\u2019s been asleep. Her restorative evening yin gives you permission to exhale. And the space in between \u2013 the ocean views, the nourishing food, the jungle air \u2013 does something to a person that\u2019s almost impossible to explain until you\u2019ve felt it.</p><p>This retreat is fully yours to shape. Add spa treatments, Costa Rican adventures, or simply let the days unfold at whatever pace your body is asking for. Your week, your way.</p><p><strong>Leave grounded, energized, and reconnected to the spark that\u2019s been waiting for you.</strong></p>", "padding_y_px": 48}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', '403e929f-18cd-4fde-a6e1-685237575195', '{"heading": "Optional Workshops", "intro": "", "tiers": [{"name": "Conscious Communication Workshop", "price": "$70", "note": "90-minute workshop"}, {"name": "Ecstatic Dance Workshop", "price": "$70", "note": "90-minute workshop"}], "padding_y_px": 32}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', 'aa9b32a9-9236-45b4-b6ea-4b386021a0d4', '{"html": "<h3>Conscious Communication Workshop</h3><p><em>90-minute workshop &mdash; $70</em></p><p><strong>There&#8217;s a version of every conversation you didn&#8217;t have.</strong></p><p>The thing you almost said. The need you talked yourself out of expressing. The moment you went quiet instead of honest &#8211; not because you didn&#8217;t have the words, but because somewhere along the way you learned it was safer not to use them.</p><p>That habit has a cost. Relationships that stay surface-level. Resentment that builds without a name. A low-grade exhaustion from editing yourself before you even open your mouth.</p><p>This workshop is 90 minutes of unlearning that.</p><p>You&#8217;ll walk away with real, practical tools for saying what you mean with clarity and care &#8211; no over-explaining, no shutdown, no wondering afterward if you handled it wrong. Language for asking for what you need. Tools for staying grounded when conversations get hard. And a clearer picture of where you hold back and why.</p><h3>Ecstatic Dance Workshop</h3><p><em>90-minute workshop &mdash; $70</em></p><p><strong>No steps to learn. No mirrors. No performing.</strong></p><p>Just music, movement, and 90 minutes of full permission to be completely in your body.</p><p>Ecstatic Dance is a movement meditation. The music builds slowly, the thinking quiets, and something underneath all that effort finally gets to breathe. Most people walk in skeptical and leave wondering why they don&#8217;t do this every week.</p><p>You don&#8217;t need to dance well. You don&#8217;t even need to like dancing. You just need to be willing to get out of your head for a little while.</p><p>You&#8217;ll leave lighter, looser, and more at home in yourself than you&#8217;ve felt in a long time.</p>", "padding_y_px": 24}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', '45734b4c-b726-4800-ad19-2ea272bddb69', '{"responsive_mode": "fixed", "role": "Lead Teacher", "name": "Dagmar Spremberg", "bio_html": "<p><strong>Reignite Your Inner Spark with Dagmar Spremberg</strong></p><p>Dagmar Spremberg made the kind of leap most people only dream about. She left city life in LA and New York, followed something deeper, and landed in Montezuma, Costa Rica \u2013 where she founded Montezuma Yoga and built a life that actually matched who she was.</p><p>That journey is woven into everything she teaches.</p><p>A 500-hour E-RYT trained in Anusara, Vinyasa Flow, and Yin Yoga, and mentored by master teachers including Elena Brower and Rod Stryker, Dagmar works with the breath as the doorway to intuition and inner knowing. Her morning flows are energizing and accessible. Her evening yin sessions are deeply restorative. Both are open to all levels, and both carry the same quiet message: you already have everything you need. This week is just about remembering it.</p><p>You\u2019ll leave with more than a yoga practice. You\u2019ll leave with the tools to keep showing up for yourself long after you\u2019re back in real life.</p>", "photo_url": "https://azvdmibriuqrmexwtrja.supabase.co/storage/v1/object/public/retreat-leader-photos/staging/58ba79c2-84ef-4dfe-82b4-e56059112124/leader/49171b107137e9a6f27ad4128395cffb041b5dc9eb0677119b3b659ce06e0457-db55b599.jpg"}'::jsonb)
on conflict do nothing;
insert into public.page_block_overrides (url_inventory_id, variant_block_id, content)
values ('f10f5251-7a7c-4084-884c-c21bb8b0a00c', '4a08c4ca-1b80-4e05-871e-97f7dafe90f3', '{}'::jsonb)
on conflict do nothing;
update public.url_inventory set cms_template_id = '2c89c7ed-da33-44b7-9455-1a97bf75b512' where id = 'f10f5251-7a7c-4084-884c-c21bb8b0a00c';

